import {WEAPONS,EVOLUTIONS,UPGRADES} from './data.js?v=cat20';
export const SYNERGIES=[{name:'전도성 거미줄',parts:['arc'],cat:'spider',desc:'거미줄에 묶인 적을 번개로 맞히면 묶인 주변 적 3마리에게 전격 전파'},{name:'불맛 연쇄점화',parts:['rocket'],cat:'chef',desc:'화상 상태의 적을 참치캔으로 처치하면 주변 적에게 화상 전파'},{name:'깃털 광선',parts:['orbit','rail'],desc:'레이저 발사 시 깃털 위치에서 조준 방향으로 보조 광선 발사'},{name:'빙결 파쇄',parts:['field','crit'],desc:'냉기 상태의 적에게 치명타가 발생하면 주변에 파편 피해'}];
export function synergyHints(id,g){return SYNERGIES.filter(s=>s.parts.includes(id)&&(!s.cat||g.classId===s.cat)&&s.parts.filter(p=>p!==id).every(p=>g.u[p])).map(s=>'조합 가능 · '+s.name).join(' / ');}
export function nextGoals(meta,g,previousBest=0){const goals=[];if(!meta.collection.owned.includes('ninja'))goals.push('닌자냥 해금까지 '+Math.max(0,300-meta.totalKills)+'마리');if(!meta.collection.owned.includes('nurse'))goals.push('닥터냥 해금까지 최고 생존 '+Math.max(0,300-meta.bestTime)+'초');if(!meta.wins)goals.push('첫 무사 퇴근으로 시크릿 고양이 해금');if(previousBest>g.t)goals.push('이전 최고 기록까지 '+Math.ceil(previousBest-g.t)+'초');else if(g.t>previousBest)goals.push('생존 최고 기록 갱신!');const candidates=EVOLUTIONS.filter(e=>!g.evolved[e.id]&&g.u[e.weapon]&&(!e.requires||g.evolved[e.requires]));candidates.sort((a,b)=>(Math.max(0,5-(g.u[a.weapon]||0))+Math.max(0,2-(g.u[a.support]||0)))-(Math.max(0,5-(g.u[b.weapon]||0))+Math.max(0,2-(g.u[b.support]||0))));if(candidates[0]){const e=candidates[0];goals.push('다음 판 목표 · '+e.name+' ('+UPGRADES.find(u=>u.id===e.weapon).name+' 5 + '+UPGRADES.find(u=>u.id===e.support).name+' 2)');}return goals.slice(0,4);}
export const buildSystems={
 synergyNotice(name,color){this.synergyNotices??={};if(this.t<(this.synergyNotices[name]||0))return;this.synergyNotices[name]=this.t+2;this.float(this.player.x,this.player.y-58,name,color,13);},
 synergyHit(e,amount,source,burning){if(source==='arc'&&this.classId==='spider'&&e.slow>0&&this.t>=(e.webChainAt||0)){e.webChainAt=this.t+.5;const targets=this.enemies.filter(n=>n!==e&&!n.dead&&n.slow>0&&Math.hypot(n.x-e.x,n.y-e.y)<200).slice(0,3);for(const n of targets){this.beams.push({x:e.x,y:e.y,tx:n.x,ty:n.y,life:.25,max:.25,color:'#deb9ff'});this.damage(n,amount*.35,'synergy');}if(targets.length)this.synergyNotice('전도성 거미줄','#deb9ff');}if(source==='rocket'&&burning&&e.dead){const targets=this.enemies.filter(n=>!n.dead&&Math.hypot(n.x-e.x,n.y-e.y)<140).slice(0,12);for(const n of targets)n.burn=Math.max(n.burn||0,3);if(targets.length){this.ring(e.x,e.y,140,'#ffae65',.4);this.synergyNotice('불맛 연쇄점화','#ffae65');}}},
 onCriticalHit(e,amount){if(!this.u.crit||e.chill<=0||this.t<(e.iceBurstAt||0))return;e.iceBurstAt=this.t+.6;const targets=this.enemies.filter(n=>n!==e&&!n.dead&&Math.hypot(n.x-e.x,n.y-e.y)<95).slice(0,8);for(const n of targets)this.damage(n,amount*.3,'synergy');if(targets.length){this.fx.push({kind:'shatter',x:e.x,y:e.y,r:95,life:.4,max:.4,color:'#bdf4ff'});this.synergyNotice('빙결 파쇄','#bdf4ff');}},
 fireFeatherLaser(){if(!this.u.orbit||!this.u.rail)return;const o=this.orbitPoints()[0];if(!o)return;const a=this.player.angle,dx=Math.cos(a),dy=Math.sin(a),length=450;this.fx.push({kind:'rail',x:o.x,y:o.y,tx:o.x+dx*length,ty:o.y+dy*length,life:.25,max:.25,color:'#a8ffdf'});for(const e of this.enemies){const x=e.x-o.x,y=e.y-o.y,forward=x*dx+y*dy;if(!e.dead&&e.warmup<=0&&forward>0&&forward<length&&Math.abs(x*dy-y*dx)<e.r+8)this.damage(e,(20+this.u.orbit*8)*this.stats.power,'synergy');}this.synergyNotice('깃털 광선','#a8ffdf');},
 swapWeapon(from,to){if(this.state!=='paused'||this.swapUsed||!this.relays.some(r=>r.active)||!WEAPONS.includes(from)||!WEAPONS.includes(to)||!this.u[from]||this.u[to]||from===to)return false;const level=Math.min(4,this.u[from]);delete this.u[from];for(const e of EVOLUTIONS)if(e.weapon===from)delete this.evolved[e.id];this.u[to]=level;this.swapUsed=true;this.bullets=[];this.traps=[];this.wells=[];this.skillObjects=[];this.evoTimers={};this.recalculate();this.callbacks.save?.();return true;}
};
