import {conceptVisuals} from './concept-visuals.js?v=cat24';
import {skillVisuals} from './skill-visuals.js?v=cat24';
import {cosmeticVisuals,normalizeLook} from './cosmetics.js?v=cat24';
import {buildSystems} from './build-systems.js?v=cat24';
import {catBosses,bossProfile} from './cat-bosses.js?v=cat24';
import {zoneFX} from './zone-fx.js?v=cat24';
import {evolutionFX} from './evolution-fx.js?v=cat24';
import {catSkills} from './cat-skills.js?v=cat24';
import {EXTRA_CATS,ACTIVE_SKILLS} from './roster.js?v=cat24';
import {SignalGame} from './interference.js?v=cat24';
import {Game} from './game.js?v=cat24';
import {WORLD,EVOLUTIONS} from './data.js?v=cat24';
const TAU=Math.PI*2;
const sprites={};
if(typeof Image!=='undefined')for(const name of ['cat-runner','cat-engineer','cat-warden','robot-cleaner','robot-toy','robot-boss',...EXTRA_CATS.map(c=>'cat-'+c.id)]){const im=new Image();im.src=new URL('./assets/'+name+'.webp',import.meta.url).href;sprites[name]=im;}
function sprite(c,name,x,y,size,flip=false){const im=sprites[name];if(!im?.complete||!im.naturalWidth)return false;const ratio=im.naturalWidth/im.naturalHeight;c.save();c.translate(x,y);if(flip)c.scale(-1,1);c.drawImage(im,-size*ratio/2,-size*.69,size*ratio,size);c.restore();return true;}
function emoji(c,text,x,y,size){c.save();c.font=size+'px "Apple Color Emoji","Segoe UI Emoji",sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(text,x,y);c.restore();}
export class CatGame extends SignalGame{
  start(...args){this.cosmetics=normalizeLook(args[1]?.cosmetics,args[1]||{});this.cosmeticFX=[];this.swapUsed=false;this.synergyNotices={};this.nextToySpawn=0;this.resetCatSkills();this.revivesUsed=0;this.awaitingRevive=false;this.orbitPhase=0;this.healAt=0;this.passiveHits=0;this.ninjaUntil=0;this.chefHealAt=0;this.sound.weapon=args[0];super.start(...args);this.nextInterference=75;}
  update(dt){if(this.state!=='playing')return;this.sound.setScene?.(this.overdrive>0?'rush':this.enemies.some(e=>e.boss&&!e.dead)?'boss':'store');super.update(dt);if(this.state!=='playing')return;this.updateCosmetics(dt);this.updateCatSkills(dt);this.updateEvolutions(dt);this.orbitPhase=(this.orbitPhase||0)+dt*1.25*Math.min(1.4,this.stats.haste);this.shake=Math.min(this.shake,3);this.hitStop=Math.min(this.hitStop,.035);}
  orbitPoints(){const n=(this.u.orbit||0)+(this.evolved.nova?2:0);return Array.from({length:n},(_,i)=>{const a=(this.orbitPhase||0)+i*TAU/n,r=this.evolved.nova?(i%2?137:101):82;return {x:this.player.x+Math.cos(a)*r,y:this.player.y+Math.sin(a)*r,a};});}
  spawnEnemy(...args){const toy=['spitter','sniper','jammer','splitter'];const limited=toy.includes(args[0])&&!this.manualSpawns;if(limited){const cap=this.t<600?4:6;if(this.t<(this.nextToySpawn||0)||this.enemies.filter(e=>!e.dead&&toy.includes(e.type)).length>=cap)return null;}const e=super.spawnEnemy(...args);if(e&&limited)this.nextToySpawn=this.t+(this.t<600?6:4.5);if(e&&!this.difficulty){const ramp=Math.min(1,this.t/600),hp=e.boss?.9:.82+.18*ramp;e.hp*=hp;e.maxHp*=hp;e.damage*=.78+.22*ramp;e.speed*=.92+.08*ramp;}return e;}
  recalculate(){super.recalculate();this.stats.pulseCd*= (ACTIVE_SKILLS[this.classId]?.cd||19)/19;if(this.skillBuff?.kind==='sprint')this.stats.speed*=1.6;if(this.classId==='nurse')this.stats.regen+=.6;if(this.classId==='wizard')this.stats.xpBonus*=1.15;if(this.classId==='astro')this.stats.pickup*=1.4;}
  dash(){const ok=super.dash();if(ok&&this.classId==='ninja')this.ninjaUntil=this.t+2;return ok;}
  hitPlayer(amount){if(this.player.invuln>0||this.state!=='playing')return;if(this.skillBuff?.kind==='guard'&&this.skillBuff.shield>0){const block=Math.min(amount,this.skillBuff.shield);this.skillBuff.shield-=block;this.skillBuff.flash=.25;amount-=block;const e=this.nearest(this.player,260);if(e){this.beams.push({x:this.player.x,y:this.player.y,tx:e.x,ty:e.y,life:.2,max:.2,color:'#ffe4a4',bread:true});this.sound.play('bread');this.damage(e,block*2,'pulse');}if(amount<=0)return;}if(this.classId==='warden'){this.passiveHits=(this.passiveHits||0)+1;if(this.passiveHits%3===0){amount*=.5;this.ring(this.player.x,this.player.y,42,'#ffdd9a',.35);}}super.hitPlayer(amount);}
  updateWeapons(dt){const fired=this.u.rail&&this.railTimer-dt<=0;super.updateWeapons(dt);if(fired)this.fireFeatherLaser();}
  pulse(){return this.activateCatSkill();}
  updateEnemy(e,dt){if(e.root>0){e.root=Math.max(0,e.root-dt);e.exposed=Math.max(0,(e.exposed||0)-dt);e.slow=Math.max(0,(e.slow||0)-dt);return;}if(e.boss){this.updateCatBoss(e,dt);return;}super.updateEnemy(e,dt);}
  drawEffects(c){this.drawCatSkills(c);super.drawEffects(c);this.drawEvolutionEffects(c);this.drawGuardShield(c);this.drawCosmeticEffects(c);this.drawSkillBursts(c);this.drawConceptEffects(c);}
  drawOrbits(c){super.drawOrbits(c);this.drawEvolutionOrbits(c);}
  drawFields(c){super.drawFields(c);this.drawEvolutionFields(c);this.drawIceZone(c);this.drawWebZones(c);this.drawSupportZones(c);this.drawConceptFields(c);}
  applyUpgrade(id){const fresh=!this.evolved[id];super.applyUpgrade(id);const e=EVOLUTIONS.find(e=>e.id===id);if(e&&fresh)this.celebrateEvolution(e);}
  updateTraps(dt){const old=this.traps.filter(t=>!t.echo&&t.life>0);super.updateTraps(dt);if(this.evolved.singularity)for(const t of old)if(t.life<=0)this.evolutionBurst(t.x,t.y,t.r,'#d8a2ff',!!this.evolved.garden);}

  explode(b){const done=b.exploded;super.explode(b);if(!done)this.fx.push({kind:'ring',canDebris:true,x:b.x,y:b.y,r:b.blast,life:.45,max:.45,color:'#ffd0a0'});if(!done&&this.evolved.barrage)this.evolutionBurst(b.x,b.y,b.blast,'#ffb76e',!!this.evolved.confetti);if(!done&&this.evolved.confetti)for(let i=0;i<8;i++)this.skillShot(b.x,b.y,i*TAU/8,'stars',b.damage*.18,400);}
  fireMain(target){const effect=this.classData.effect;if(!effect){super.fireMain(target);return;}const p=this.player,a=p.angle,count=(effect==='stars'?5:effect==='ice'?3:1)+(this.u.multi||0),speed=effect==='gravity'?360:effect==='return'?480:700;p.shotCd=this.classData.interval/this.stats.haste;for(let i=0;i<count;i++){const angle=a+(i-(count-1)/2)*.17;this.bullets.push({x:p.x,y:p.y,px:p.x,py:p.y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:effect==='return'?1.5:this.stats.range/speed,age:0,r:effect==='gravity'?9:5,damage:this.stats.damage,pierce:effect==='return'?999:(this.u.pierce||0)+(['pierce','web','gravity'].includes(effect)?2:0),hit:[],type:'bullet',catEffect:effect,color:this.classData.color});}this.sound.play('weapon-'+effect);}
  updateBullet(b,dt){if(b.catEffect==='return'){b.age=(b.age||0)+dt;if(b.age>.65){if(!b.returning){b.returning=true;b.hit=[];b.pierce=999;}const a=Math.atan2(this.player.y-b.y,this.player.x-b.x);b.vx=Math.cos(a)*540;b.vy=Math.sin(a)*540;if(Math.hypot(b.x-this.player.x,b.y-this.player.y)<18)b.life=0;}}this.activeCatBullet=b;super.updateBullet(b,dt);this.activeCatBullet=null;}
  kill(e){const wasDead=e.dead,slowed=e.slow>0,burning=e.burn>0;super.kill(e);if(wasDead)return;this.emitCosmetic(e);this.sound.play('enemy-down',{large:e.boss||e.r>=25,boss:!!e.boss});if(this.settings.particles&&this.fx.length<360){const color=e.chill>0?'#b5ecff':e.burn>0?'#ffc080':'#b6ffe6',r=Math.min(90,e.r*(e.boss?2.5:1.8));this.fx.push({kind:'shatter',x:e.x,y:e.y,r,life:.4,max:.4,color},{kind:'burst',x:e.x,y:e.y,r:r*.8,life:.22,max:.22,color});this.particles(e.x,e.y,e.boss?16:5,color,e.boss?150:85);}if(this.classId==='spider'&&slowed)this.player.dashCd=Math.max(0,this.player.dashCd-.4);if(this.classId==='spark'&&this.kills%5===0)this.player.pulseCd=Math.max(0,this.player.pulseCd-1);if(this.classId==='chef'&&burning&&this.t>=(this.chefHealAt||0)){this.chefHealAt=this.t+1.5;this.player.hp=Math.min(this.player.maxHp,this.player.hp+3);this.float(this.player.x,this.player.y-35,'+3','#ffcc91',12);}}
  damage(e,amount,source){if(e.dead)return;const burning=e.burn>0;if(this.classId==='frost'&&e.chill>0)amount*=1.15;if(this.classId==='ninja'&&source==='bullet'&&this.ninjaUntil>this.t){amount*=1.6;this.ninjaUntil=0;this.float(e.x,e.y-e.r,'그림자 일격','#ffbdcf',12);}if(!e.dead&&source!=='field'&&source!=='cat-flame')this.sound.play('impact');const effect=source==='bullet'?this.activeCatBullet?.catEffect:null;super.damage(e,amount,source);this.synergyHit(e,amount,source,burning);if(!effect)return;if(effect==='freeze'){e.root=e.boss?.35:2;e.chill=3;this.fx.push({kind:'ring',skillBurst:'ice',x:e.x,y:e.y,r:30,life:.35,max:.35,color:'#b5edff'});}if(effect==='web'){e.slow=Math.max(e.slow||0,2);this.ring(e.x,e.y,24,'#d5b5ff',.4);}if(effect==='ice'){e.slow=Math.max(e.slow||0,1.5);e.chill=2;}if(effect==='heal'&&this.t>=(this.healAt||0)){this.healAt=this.t+2;this.player.hp=Math.min(this.player.maxHp,this.player.hp+2);this.ring(this.player.x,this.player.y,25,'#97f4cf',.25);}if(effect==='flame'){e.burn=2;for(const n of this.enemies)if(n!==e&&!n.dead&&Math.hypot(n.x-e.x,n.y-e.y)<70){n.burn=2;this.damage(n,amount*.4,'cat-flame');}this.ring(e.x,e.y,70,'#ffae68',.3);}if(effect==='chain'){const n=this.nearest(e,190,new Set([e.id]));if(n){this.beams.push({x:e.x,y:e.y,tx:n.x,ty:n.y,life:.2,max:.2,color:'#ffed91'});this.damage(n,amount*.6,'arc');}}if(effect==='gravity'){for(const n of this.enemies)if(!n.dead&&!n.boss){const d=Math.hypot(n.x-e.x,n.y-e.y);if(d>5&&d<150){n.x+=(e.x-n.x)*.25;n.y+=(e.y-n.y)*.25;n.slow=1;}}this.ring(e.x,e.y,100,'#b9d4ff',.3);}}
  drawBullets(c){super.drawBullets(c);this.drawEvolutionProjectiles(c);for(const b of this.bullets){if(!b.catEffect||!this.visible(b.x,b.y,25))continue;c.save();c.translate(b.x,b.y);c.rotate(Math.atan2(b.vy,b.vx));c.strokeStyle=b.color;c.lineWidth=1.5;if(b.catEffect==='freeze'){c.fillStyle='#aee9ff';c.strokeStyle='#efffff';c.beginPath();c.moveTo(21,0);c.lineTo(-9,-5);c.lineTo(-4,0);c.lineTo(-9,5);c.closePath();c.fill();c.stroke();if(this.settings.particles){c.globalAlpha=.5;c.beginPath();c.moveTo(-9,0);c.lineTo(-29,0);c.stroke();}}else if(b.catEffect==='web'){for(let i=0;i<3;i++){c.rotate(TAU/3);c.beginPath();c.moveTo(-9,0);c.lineTo(9,0);c.stroke();}c.beginPath();c.arc(0,0,7,0,TAU);c.stroke();}else if(b.catEffect==='return'){c.beginPath();c.arc(0,0,11,-1.2,1.2);c.stroke();}else if(['stars','pierce','ice'].includes(b.catEffect)){c.beginPath();c.moveTo(10,0);c.lineTo(0,7);c.lineTo(-10,0);c.lineTo(0,-7);c.closePath();c.stroke();}else{c.beginPath();c.arc(0,0,b.r+3,0,TAU);c.stroke();}c.restore();}this.drawConceptProjectiles(c);}
  finish(won){if(!won&&this.classId==='moon'&&!this.revivesUsed&&!this.awaitingRevive){this.awaitingRevive=true;this.state='ended';this.revive(.35);this.toast('아홉 번째 밤 · 자동 부활',false,2);this.sound.play('level');return;}if(!won&&!this.revivesUsed&&!this.awaitingRevive&&this.callbacks.downed){this.awaitingRevive=true;this.state='ended';this.keys.clear();this.touch={x:0,y:0};this.callbacks.downed();return;}super.finish(won);}
  revive(ratio=.6){if(!this.awaitingRevive||this.revivesUsed)return false;this.awaitingRevive=false;this.revivesUsed=1;this.player.hp=this.player.maxHp*ratio;this.player.invuln=3;this.hostile=[];this.hazards=[];this.lines=[];this.waves=[];this.hitStop=0;for(const e of this.enemies){const dx=e.x-this.player.x,dy=e.y-this.player.y,d=Math.hypot(dx,dy);if(d<220&&!e.dead){const a=d?Math.atan2(dy,dx):0;e.x=Math.max(-WORLD+e.r,Math.min(WORLD-e.r,this.player.x+Math.cos(a)*240));e.y=Math.max(-WORLD+e.r,Math.min(WORLD-e.r,this.player.y+Math.sin(a)*240));}}this.state='playing';this.callbacks.resume?.();this.callbacks.save?.();return true;}
  declineRevive(){if(!this.awaitingRevive)return;this.awaitingRevive=false;this.revivesUsed=1;this.state='playing';super.finish(false);}
  serialize(){const state=this.state,hp=this.player.hp;if(this.awaitingRevive){this.state='paused';this.player.hp=1;}const data=super.serialize();if(data){data.player={...data.player};data.cats={revivesUsed:this.revivesUsed||0,awaitingRevive:!!this.awaitingRevive,orbitPhase:this.orbitPhase||0,healAt:this.healAt||0,passiveHits:this.passiveHits||0,ninjaUntil:this.ninjaUntil||0,chefHealAt:this.chefHealAt||0,nextToySpawn:this.nextToySpawn||0,swapUsed:!!this.swapUsed,skillObjects:this.skillObjects,skillBuff:this.skillBuff,evoTimers:this.evoTimers};}this.state=state;this.player.hp=hp;return data;}
  restore(data){this.swapUsed=!!data?.cats?.swapUsed;this.synergyNotices={};this.nextToySpawn=data?.cats?.nextToySpawn||0;this.resetCatSkills();this.skillObjects=data?.cats?.skillObjects||[];this.skillBuff=data?.cats?.skillBuff||null;this.evoTimers=data?.cats?.evoTimers||{};this.revivesUsed=data?.cats?.revivesUsed||0;this.awaitingRevive=false;this.orbitPhase=data?.cats?.orbitPhase||0;this.healAt=data?.cats?.healAt||0;this.passiveHits=data?.cats?.passiveHits||0;this.ninjaUntil=data?.cats?.ninjaUntil||0;this.chefHealAt=data?.cats?.chefHealAt||0;const ok=super.restore(data);if(ok&&data.cats?.awaitingRevive){this.player.hp=0;this.awaitingRevive=true;this.state='ended';this.callbacks.downed?.();}return ok;}
  constructor(...args){super(...args);if(typeof Image!=='undefined'){this.groundImage=new Image();this.groundImage.src=new URL('./assets/convenience-floor.webp',import.meta.url).href;}}
  render(delta){if(this.state==='menu'){this.visualTime+=Math.min(delta,.05);return;}SignalGame.prototype.render.call(this,delta);}
  drawFloor(c){
    const left=this.camera.x-this.w/(2*this.zoom),top=this.camera.y-this.h/(2*this.zoom),width=this.w/this.zoom,height=this.h/this.zoom;
    c.save();c.fillStyle='#18282e';c.fillRect(left,top,width,height);
    if(this.groundImage?.complete&&this.groundImage.naturalWidth){c.drawImage(this.groundImage,-WORLD,-WORLD,WORLD*2,WORLD*2);for(const [x,y] of [[-360,-250],[360,-250],[-360,260],[360,260]])c.drawImage(this.groundImage,145,140,195,105,x-115,y-62,230,124);c.fillStyle='#08162038';c.fillRect(-WORLD,-WORLD,WORLD*2,WORLD*2);}
    c.strokeStyle='#93e5cf88';c.lineWidth=2;c.setLineDash([12,10]);c.beginPath();c.arc(0,0,150,0,TAU);c.stroke();c.setLineDash([]);c.font='600 16px sans-serif';c.textAlign='center';c.fillStyle='#d5f3e7';c.fillText('퇴근 집합 장소',0,177);
    c.strokeStyle='#ffd18a66';c.lineWidth=3;c.strokeRect(-WORLD,-WORLD,WORLD*2,WORLD*2);
    c.fillStyle='#080f17';if(left<-WORLD)c.fillRect(left,top,-WORLD-left,height);if(left+width>WORLD)c.fillRect(WORLD,top,left+width-WORLD,height);if(top<-WORLD)c.fillRect(left,top,width,-WORLD-top);if(top+height>WORLD)c.fillRect(left,WORLD,width,top+height-WORLD);c.restore();
  }
  drawPlayer(c,x,y,a){this.drawAim(c,x,y,a);c.save();const p=this.player;const moving=Math.hypot(p.moveX||0,p.moveY||0)>0&&(this.keys.size>0||Math.hypot(this.touch.x,this.touch.y)>0);if(p.invuln>0&&Math.floor(this.visualTime*15)%2)c.globalAlpha=.5;const bob=moving?Math.sin(this.visualTime*17)*2:Math.sin(this.visualTime*3)*.7;c.strokeStyle='#92e8d0';c.lineWidth=1.5;c.beginPath();c.ellipse(x,y+12,23,11,0,0,TAU);c.stroke();c.fillStyle='#00000088';c.beginPath();c.ellipse(x,y+11,16,7,0,0,TAU);c.fill();if(Math.cos(a)>.25)this.catFacingLeft=false;else if(Math.cos(a)<-.25)this.catFacingLeft=true;if(!sprite(c,'cat-'+(this.classId||'runner'),x,y+bob,54,!!this.catFacingLeft))emoji(c,'🐱',x,y,35);this.drawOutfit(c,x,y+bob);if(this.overdrive>0){c.strokeStyle='#e49530';c.lineWidth=3;c.beginPath();c.arc(x,y,34,0,TAU);c.stroke();}c.restore();}
  drawEnemy(c,e){this.drawCatEnemy(c,e);this.drawEnemyStatus(c,e);if(e.boss){const b=bossProfile(e);c.save();c.strokeStyle=b.color;c.lineWidth=3;c.beginPath();c.arc(e.x,e.y,e.r+12,-Math.PI/2,-Math.PI/2+Math.PI*2*e.hp/e.maxHp);c.stroke();c.restore();}}
  drawCatEnemy(c,e){c.save();if(e.warmup>0)c.globalAlpha=.4;if(e.flash>0)c.globalAlpha=.65;const boss=e.boss||['final','sentinel','elite','brute'].includes(e.type);const name=e.boss?bossProfile(e).sprite:boss?'robot-boss':['spitter','sniper','jammer','splitter'].includes(e.type)?'robot-toy':'robot-cleaner';c.fillStyle='#00000088';c.beginPath();c.ellipse(e.x,e.y+e.r*.65,e.r*.9,e.r*.3,0,0,TAU);c.fill();if(!sprite(c,name,e.x,e.y,Math.max(26,e.r*2.7),Math.cos(e.angle)<0))emoji(c,'🤖',e.x,e.y,e.r*2);if(e.shielded){c.strokeStyle='#a782c9';c.lineWidth=3;c.beginPath();c.arc(e.x,e.y,e.r+9,0,TAU);c.stroke();}if(e.chill>0){c.strokeStyle='#58a7c5';c.lineWidth=2;c.beginPath();c.arc(e.x,e.y,e.r+5,0,TAU);c.stroke();}if(e.hp<e.maxHp){c.fillStyle='#271c2a';c.fillRect(e.x-e.r,e.y-e.r-20,e.r*2,4);c.fillStyle='#ff788d';c.fillRect(e.x-e.r,e.y-e.r-20,e.r*2*Math.max(0,e.hp/e.maxHp),4);}c.restore();}
  drawDrone(c,x,y,a){c.save();c.translate(x,y);c.rotate(a);emoji(c,'🪶',0,0,27);c.restore();}
  drawRelays(c){for(const r of this.relays){if(!this.visible(r.x,r.y,170))continue;const open=this.t>=r.unlock,color=r.active?'#8df2cc':open?'#ffd18a':'#8494ac';c.save();c.globalAlpha=open||r.active?1:.5;c.fillStyle=r.active?'#79b99122':'#e0a65520';c.strokeStyle=color;c.lineWidth=3;c.beginPath();c.arc(r.x,r.y,107,0,TAU);c.fill();c.stroke();if(r.charge>0){c.lineWidth=6;c.beginPath();c.arc(r.x,r.y,112,-Math.PI/2,-Math.PI/2+TAU*r.charge/10);c.stroke();}emoji(c,r.active?'🍱':'📦',r.x,r.y,51);c.font='700 16px sans-serif';c.textAlign='center';c.fillStyle=color;c.fillText('간식 창고 '+(r.id+1),r.x,r.y-130);c.font='14px sans-serif';if(r.active)c.fillText('회수 완료',r.x,r.y+139);c.restore();}}
  drawLoot(c){for(const l of this.loot){if(!this.visible(l.x,l.y,24))continue;if(l.type==='xp'){c.fillStyle=l.value>20?'#ffe29a':'#a7efce';c.strokeStyle='#d9ffe8';c.lineWidth=1;c.beginPath();c.arc(l.x,l.y,l.value>20?6:4,0,TAU);c.fill();c.stroke();}else emoji(c,l.type==='med'?'🥛':l.type==='magnet'?'🧲':'🍪',l.x,l.y+Math.sin(this.visualTime*3)*2,24);}}
}
Object.assign(CatGame.prototype,catSkills,evolutionFX,zoneFX,catBosses,buildSystems,cosmeticVisuals,skillVisuals,conceptVisuals);
export {CatGame as SignalGame};
