import {SignalGame} from './interference.js?v=cat1';
import {Game} from './game.js?v=cat1';
import {WORLD} from './data.js?v=cat1';
const TAU=Math.PI*2;
const sprites={};
if(typeof Image!=='undefined')for(const name of ['cat-runner','cat-engineer','cat-warden','robot-cleaner','robot-toy','robot-boss']){const im=new Image();im.src=new URL('./assets/'+name+'.webp',import.meta.url).href;sprites[name]=im;}
function sprite(c,name,x,y,size,flip=false){const im=sprites[name];if(!im?.complete||!im.naturalWidth)return false;const ratio=im.naturalWidth/im.naturalHeight;c.save();c.translate(x,y);if(flip)c.scale(-1,1);c.drawImage(im,-size*ratio/2,-size*.69,size*ratio,size);c.restore();return true;}
function emoji(c,text,x,y,size){c.save();c.font=size+'px "Apple Color Emoji","Segoe UI Emoji",sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(text,x,y);c.restore();}
export class CatGame extends SignalGame{
  render(delta){this.hitStop=Math.max(0,(this.hitStop||0)-delta);this.glitch=0;if(this.state==='menu'){this.visualTime+=Math.min(delta,.05);return;}Game.prototype.render.call(this,delta);}
  drawFloor(c){const left=this.camera.x-this.w/(2*this.zoom),top=this.camera.y-this.h/(2*this.zoom),right=left+this.w/this.zoom,bottom=top+this.h/this.zoom;c.fillStyle='#eee9d8';c.fillRect(left,top,right-left,bottom-top);const step=100;for(let x=Math.floor(left/step)*step;x<right;x+=step)for(let y=Math.floor(top/step)*step;y<bottom;y+=step){if((Math.floor(x/step)+Math.floor(y/step))%2===0){c.fillStyle='#e6e2cf';c.fillRect(x+2,y+2,step-4,step-4);}}c.strokeStyle='#98adc044';c.lineWidth=8;c.strokeRect(-WORLD,-WORLD,WORLD*2,WORLD*2);c.fillStyle='#d4dde4';if(left<-WORLD)c.fillRect(left,top,-WORLD-left,bottom-top);if(right>WORLD)c.fillRect(WORLD,top,right-WORLD,bottom-top);if(top<-WORLD)c.fillRect(left,top,right-left,-WORLD-top);if(bottom>WORLD)c.fillRect(left,WORLD,right-left,bottom-WORLD);
    c.save();c.setLineDash([10,12]);c.strokeStyle='#7596c3';c.lineWidth=3;c.beginPath();c.arc(0,0,150,0,TAU);c.stroke();c.setLineDash([]);c.fillStyle='#c1d2e54a';c.fill();c.font='700 19px sans-serif';c.fillStyle='#627e9f';c.textAlign='center';c.fillText('퇴근 출입구',0,190);emoji(c,'🏠',0,0,48);c.restore();
    for(const r of this.relays){c.save();c.font='700 28px sans-serif';c.fillStyle='#7892af55';c.textAlign='center';c.fillText(['간식 코너','냉장 코너','야식 코너'][r.id],r.x,r.y-190);c.restore();}
  }
  drawPlayer(c,x,y,a){this.drawAim(c,x,y,a);c.save();const p=this.player;const moving=Math.hypot(p.moveX||0,p.moveY||0)>0&&(this.keys.size>0||Math.hypot(this.touch.x,this.touch.y)>0);if(p.invuln>0&&Math.floor(this.visualTime*15)%2)c.globalAlpha=.5;const bob=moving?Math.sin(this.visualTime*17)*2:Math.sin(this.visualTime*3)*.7;c.fillStyle='#526a8533';c.beginPath();c.ellipse(x,y+11,16,7,0,0,TAU);c.fill();if(!sprite(c,'cat-'+(this.classId||'runner'),x,y+bob,54,Math.cos(a)<0))emoji(c,'🐱',x,y,35);if(this.overdrive>0){c.strokeStyle='#e49530';c.lineWidth=3;c.beginPath();c.arc(x,y,34,0,TAU);c.stroke();}c.restore();}
  drawEnemy(c,e){c.save();if(e.warmup>0)c.globalAlpha=.4;if(e.flash>0)c.globalAlpha=.65;const boss=e.boss||['final','sentinel','elite','brute'].includes(e.type);const name=boss?'robot-boss':['spitter','sniper','jammer','splitter'].includes(e.type)?'robot-toy':'robot-cleaner';c.fillStyle='#526a8522';c.beginPath();c.ellipse(e.x,e.y+e.r*.65,e.r*.9,e.r*.3,0,0,TAU);c.fill();if(!sprite(c,name,e.x,e.y,Math.max(26,e.r*2.7),Math.cos(e.angle)<0))emoji(c,'🤖',e.x,e.y,e.r*2);if(e.shielded){c.strokeStyle='#a782c9';c.lineWidth=3;c.beginPath();c.arc(e.x,e.y,e.r+9,0,TAU);c.stroke();}if(e.chill>0){c.strokeStyle='#58a7c5';c.lineWidth=2;c.beginPath();c.arc(e.x,e.y,e.r+5,0,TAU);c.stroke();}if(e.hp<e.maxHp){c.fillStyle='#c4adab';c.fillRect(e.x-e.r,e.y-e.r-20,e.r*2,4);c.fillStyle='#ba6178';c.fillRect(e.x-e.r,e.y-e.r-20,e.r*2*Math.max(0,e.hp/e.maxHp),4);}c.restore();}
  drawDrone(c,x,y,a){c.save();c.translate(x,y);c.rotate(a);emoji(c,'🪶',0,0,27);c.restore();}
  drawRelays(c){for(const r of this.relays){if(!this.visible(r.x,r.y,170))continue;const open=this.t>=r.unlock,color=r.active?'#568c76':open?'#d57a3d':'#8e9eae';c.save();c.globalAlpha=open||r.active?1:.5;c.fillStyle=r.active?'#79b99122':'#e0a65520';c.strokeStyle=color;c.lineWidth=3;c.beginPath();c.arc(r.x,r.y,107,0,TAU);c.fill();c.stroke();if(r.charge>0){c.lineWidth=6;c.beginPath();c.arc(r.x,r.y,112,-Math.PI/2,-Math.PI/2+TAU*r.charge/12);c.stroke();}emoji(c,r.active?'🍱':'📦',r.x,r.y,51);c.font='700 16px sans-serif';c.textAlign='center';c.fillStyle=color;c.fillText('간식 창고 '+(r.id+1),r.x,r.y-130);c.font='14px sans-serif';c.fillText(r.active?'간식 회수 완료':open?'원 안에서 12초 기다리기':'아직 준비 중',r.x,r.y+139);c.restore();}}
  drawLoot(c){for(const l of this.loot){if(!this.visible(l.x,l.y,24))continue;if(l.type==='xp'){c.fillStyle=l.value>20?'#dc9545':'#c19656';c.strokeStyle='#a67944';c.lineWidth=1;c.beginPath();c.arc(l.x,l.y,l.value>20?6:4,0,TAU);c.fill();c.stroke();}else emoji(c,l.type==='med'?'🥛':l.type==='magnet'?'🧲':'🍪',l.x,l.y+Math.sin(this.visualTime*3)*2,24);}}
}
export {CatGame as SignalGame};
