// Recognizable convenience-store props; visual only, no combat RNG.
const TAU=Math.PI*2;
function loaf(c,w,h){c.beginPath();c.moveTo(-w*.8,h);c.lineTo(-w*.8,-h*.25);c.bezierCurveTo(-w*1.25,-h*.45,-w,-h*1.2,-w*.45,-h);c.quadraticCurveTo(0,-h*1.25,w*.45,-h);c.bezierCurveTo(w,-h*1.2,w*1.25,-h*.45,w*.8,-h*.25);c.lineTo(w*.8,h);c.quadraticCurveTo(0,h*1.12,-w*.8,h);c.closePath();}
function fish(c,x,y){c.beginPath();c.ellipse(x,y,5,3,0,0,TAU);c.fill();c.beginPath();c.moveTo(x-4,y);c.lineTo(x-9,y-4);c.lineTo(x-9,y+4);c.closePath();c.fill();}
function can(c){c.fillStyle='#b4d5da';c.strokeStyle='#ecffff';c.lineWidth=1.5;c.fillRect(-11,-8,22,16);c.strokeRect(-11,-8,22,16);c.fillStyle='#ed9671';c.fillRect(-10,-4,20,9);c.fillStyle='#fff4d6';fish(c,2,0);for(const y of [-8,8]){c.fillStyle='#cce5e8';c.beginPath();c.ellipse(0,y,11,3,0,0,TAU);c.fill();c.stroke();}c.strokeStyle='#5e878c';c.beginPath();c.ellipse(0,-8,3,1.5,0,0,TAU);c.stroke();}
function yarn(c,x,y,r){c.save();c.translate(x,y);c.fillStyle='#f1abc9';c.strokeStyle='#8d4b77';c.lineWidth=1.3;c.beginPath();c.arc(0,0,r,0,TAU);c.fill();c.stroke();for(let i=-1;i<=1;i++){c.beginPath();c.ellipse(i*r*.25,0,r*.42,r*.85,.5,0,TAU);c.stroke();}c.restore();}
export const conceptVisuals={
 drawGuardShield(c){const b=this.skillBuff;if(b?.kind!=='guard'||b.shield<=0)return;const p=this.player,q=Math.min(1,b.shield/(p.maxHp*.45)),flash=(b.flash||0)/.25;c.save();c.translate(p.x,p.y-3);c.scale(1+flash*.06,1+flash*.06);loaf(c,44,36);c.fillStyle='#ffe3a21a';c.fill();c.strokeStyle=flash?'#fff3cd':'#d89b55';c.lineWidth=7;c.stroke();c.strokeStyle='#ffe5ae';c.lineWidth=2;c.stroke();c.fillStyle='#fff2c8';for(const [x,y] of [[-30,-18],[29,-15],[-29,20],[30,21]]){c.beginPath();c.ellipse(x,y,2,3,.4,0,TAU);c.fill();}c.fillStyle='#684928';c.fillRect(-22,43,44,4);c.fillStyle='#f3cf87';c.fillRect(-22,43,44*q,4);c.restore();},
 drawConceptProjectiles(c){for(const b of this.bullets){if(!this.visible(b.x,b.y,35))continue;if(b.type==='rocket'){c.save();c.translate(b.x,b.y);c.rotate(Math.atan2(b.vy,b.vx)+Math.PI/2);can(c);c.restore();}else if(b.catEffect==='stars'){c.save();c.translate(b.x,b.y);c.fillStyle='#e1c4ff';c.strokeStyle='#fff3ff';c.lineWidth=1;c.beginPath();for(let i=0;i<10;i++){const a=i*Math.PI/5-Math.PI/2,r=i%2?3:8;c.lineTo(Math.cos(a)*r,Math.sin(a)*r);}c.closePath();c.fill();c.stroke();c.restore();}}},
 drawConceptFields(c){const p=this.player;if(this.u.field){c.save();c.translate(p.x-34,p.y+24);c.lineWidth=1.5;c.strokeStyle='#d2f4ff';if(this.evolved.absolute){c.fillStyle='#5c97b7';c.fillRect(-14,-9,28,19);c.strokeRect(-14,-9,28,19);c.fillStyle='#b5e5ed';c.beginPath();c.moveTo(-14,-9);c.lineTo(-11,-19);c.lineTo(16,-19);c.lineTo(14,-9);c.closePath();c.fill();c.stroke();c.fillStyle='#ebffff';c.fillRect(-6,-6,7,7);c.fillRect(3,-8,7,7);}else{c.fillStyle='#77bbd6';c.beginPath();c.moveTo(-10,-13);c.quadraticCurveTo(0,-10,10,-13);c.lineTo(12,13);c.quadraticCurveTo(0,10,-12,13);c.closePath();c.fill();c.stroke();c.fillStyle='#e3faff';c.fillRect(-5,-2,10,3);c.fillRect(-1,-6,3,11);}c.restore();}
 for(const z of this.skillObjects||[]){if(!this.visible(z.x,z.y,80))continue;if(z.kind==='clinic'){c.save();c.translate(z.x,z.y-22);c.fillStyle='#e4fff0';c.strokeStyle='#88cbb1';c.lineWidth=2;c.fillRect(-23,-8,46,31);c.strokeRect(-23,-8,46,31);c.strokeRect(-8,-15,16,7);c.fillStyle='#63aa8b';c.fillRect(-11,4,22,5);c.fillRect(-3,-4,6,22);c.rotate(.3);c.fillStyle='#f4b888';c.fillRect(26,-5,10,30);c.fillStyle='#fff2d9';fish(c,32,10);c.restore();}if(z.kind==='flame'){c.save();c.translate(z.x,z.y);c.rotate(z.angle||0);c.strokeStyle='#ded7bc';c.lineWidth=5;c.beginPath();c.moveTo(10,0);c.lineTo(32,0);c.stroke();c.fillStyle='#374c52';c.strokeStyle='#adc8ca';c.lineWidth=2;c.beginPath();c.ellipse(39,0,12,17,0,0,TAU);c.fill();c.stroke();c.fillStyle='#ffa866';c.fillRect(35,-7,7,5);c.fillRect(40,2,6,6);c.restore();}}
 },
 drawConceptEffects(c){for(const b of this.beams.slice(-36)){if(b.thread){const q=Math.max(0,b.life/.2);c.save();c.globalAlpha=q*.9;c.strokeStyle='#ffc2dd';c.lineWidth=2;c.beginPath();c.moveTo(b.x,b.y);const dx=b.tx-b.x,dy=b.ty-b.y,d=Math.hypot(dx,dy)||1;for(let i=1;i<=20;i++){const t=i/20,s=Math.sin(t*Math.PI*6)*6;c.lineTo(b.x+dx*t-dy/d*s,b.y+dy*t+dx/d*s);}c.stroke();yarn(c,b.x,b.y,9);c.restore();}if(b.bread){const t=1-Math.max(0,b.life/.2);c.save();c.translate(b.x+(b.tx-b.x)*t,b.y+(b.ty-b.y)*t);c.rotate(t*3);loaf(c,10,8);c.fillStyle='#ffe1a1';c.strokeStyle='#b78143';c.lineWidth=2;c.fill();c.stroke();c.restore();}}
 for(const f of this.fx){if(!f.canDebris)continue;const q=f.life/f.max;c.save();c.translate(f.x,f.y);c.globalAlpha=q;c.strokeStyle='#d8f1f1';c.lineWidth=2;for(let i=0;i<(this.settings.particles?6:3);i++){const a=i*TAU/(this.settings.particles?6:3),r=(1-q)*Math.min(f.r,95);c.save();c.translate(Math.cos(a)*r,Math.sin(a)*r);c.rotate(a+q*4);if(!i){c.beginPath();c.ellipse(0,0,10,4,0,0,TAU);c.stroke();}else{c.fillStyle=i%2?'#e7a079':'#bedade';c.fillRect(-4,-2,8,4);}c.restore();}c.restore();}}
};
