// Visual-only layers: no combat RNG, collision radius or damage changes.
const TAU=Math.PI*2;
const COLORS={orbit:'#9bffe0',arc:'#ffed8c',rocket:'#ffb76e',field:'#8ce6ff',rail:'#fff19d',mine:'#d8a2ff'};
function circle(c,x,y,r){c.beginPath();c.arc(x,y,Math.max(0,r),0,TAU);}
function line(c,x,y,tx,ty){c.beginPath();c.moveTo(x,y);c.lineTo(tx,ty);}
export const evolutionFX={
 evolutionBurst(x,y,r,color,final=false){if(!this.settings.particles||this.fx.length>420)return;this.fx.push({kind:'evo-burst',x,y,r,color,final,life:final?.85:.55,max:final?.85:.55});},
 celebrateEvolution(e){const p=this.player;this.evolutionBurst(p.x,p.y,e.requires?250:180,COLORS[e.weapon],!!e.requires);},
 drawEvolutionOrbits(c){if(!this.settings.particles||!this.evolved.nova)return;const p=this.player,final=this.evolved.aegis;c.save();c.strokeStyle=final?'#fff2ab':'#9bffe0';c.lineCap='round';for(const o of this.orbitPoints()){const r=Math.hypot(o.x-p.x,o.y-p.y);for(let i=0;i<3;i++){c.globalAlpha=.32-i*.08;c.lineWidth=7-i*2;c.beginPath();c.arc(p.x,p.y,r,o.a-.65-i*.1,o.a);c.stroke();}c.globalAlpha=.85;circle(c,o.x,o.y,final?12:7);c.stroke();}if(final){c.globalAlpha=.35;c.lineWidth=2;c.setLineDash([15,10]);circle(c,p.x,p.y,155);c.stroke();}c.restore();},
 drawEvolutionFields(c){if(!this.settings.particles)return;const p=this.player,t=this.visualTime;c.save();
  if(this.evolved.absolute){const r=100+(this.u.field||0)*13+55,n=this.evolved.blizzard?18:10;c.strokeStyle='#b7f5ff';c.globalAlpha=.45;c.lineWidth=2;for(let i=0;i<n;i++){const a=i*TAU/n+t*.12,x=p.x+Math.cos(a)*r,y=p.y+Math.sin(a)*r;c.beginPath();c.moveTo(x+Math.cos(a)*11,y+Math.sin(a)*11);c.lineTo(x-Math.sin(a)*5,y+Math.cos(a)*5);c.lineTo(x-Math.cos(a)*11,y-Math.sin(a)*11);c.lineTo(x+Math.sin(a)*5,y-Math.cos(a)*5);c.closePath();c.stroke();}c.globalAlpha=.22;circle(c,p.x,p.y,r*(.7+.2*((t*.5)%1)));c.stroke();}
  if(this.evolved.singularity){c.strokeStyle=this.evolved.garden?'#ffccff':'#c5a3ff';c.lineWidth=2;for(const w of this.wells.slice(-12)){if(!this.visible(w.x,w.y,w.r))continue;c.globalAlpha=.5;for(let j=0;j<3;j++){c.beginPath();for(let i=0;i<=24;i++){const q=i/24,a=q*TAU*1.3+t*1.8+j*TAU/3,r=12+q*(w.r-12),x=w.x+Math.cos(a)*r,y=w.y+Math.sin(a)*r;if(i)c.lineTo(x,y);else c.moveTo(x,y);}c.stroke();}c.globalAlpha=.6;circle(c,w.x,w.y,23);c.stroke();}}
 c.restore();},
 drawEvolutionProjectiles(c){if(!this.settings.particles||!this.evolved.barrage)return;c.save();c.lineCap='round';for(const b of this.bullets){if(b.type!=='rocket'||!this.visible(b.x,b.y,60))continue;const a=Math.atan2(b.vy,b.vx),n=this.evolved.confetti?3:2;for(let i=0;i<n;i++){const d=20+i*15;c.strokeStyle=i%2?'#ffe7a4':'#ff955c';c.globalAlpha=.7-i*.18;c.lineWidth=8-i*2;line(c,b.x-Math.cos(a)*d,b.y-Math.sin(a)*d,b.x,b.y);c.stroke();}}c.restore();},
 drawEvolutionEffects(c){if(!this.settings.particles)return;c.save();c.lineCap='round';
  for(const b of this.beams.slice(-36)){if(!b.evo)continue;const q=Math.max(0,b.life/b.max),dx=b.tx-b.x,dy=b.ty-b.y,len=Math.hypot(dx,dy)||1;c.beginPath();c.moveTo(b.x,b.y);for(let i=1;i<9;i++){const zig=Math.sin(i*9.3+b.x)*13;c.lineTo(b.x+dx*i/9-dy/len*zig,b.y+dy*i/9+dx/len*zig);}c.lineTo(b.tx,b.ty);for(const [width,opacity,color] of [[b.final?17:11,.16,'#ffdf67'],[5,.65,'#ffec97'],[1.5,.95,'#fffdec']]){c.lineWidth=width;c.globalAlpha=q*opacity;c.strokeStyle=color;c.stroke();}}
  for(const f of this.fx.slice(-420)){const q=Math.max(0,f.life/f.max);if(f.kind==='rail'&&f.evo){c.strokeStyle=f.final?'#b6fbff':'#fff5b6';line(c,f.x,f.y,f.tx,f.ty);c.globalAlpha=q*.18;c.lineWidth=f.final?32:22;c.stroke();c.globalAlpha=q*.85;c.lineWidth=6;c.stroke();c.strokeStyle='#ffffff';c.lineWidth=2;c.stroke();const dx=f.tx-f.x,dy=f.ty-f.y,d=Math.hypot(dx,dy)||1;c.globalAlpha=q*.5;c.lineWidth=1;for(const side of [-1,1]){line(c,f.x-dy/d*12*side,f.y+dx/d*12*side,f.tx-dy/d*12*side,f.ty+dx/d*12*side);c.stroke();}}
   if(f.kind==='evo-burst'){const r=f.r*(1-q*.8);c.strokeStyle=f.color;c.globalAlpha=q*.7;c.lineWidth=4*q+1;circle(c,f.x,f.y,r);c.stroke();c.globalAlpha=q*.35;circle(c,f.x,f.y,r*.72);c.stroke();const n=f.final?20:12;c.globalAlpha=q*.85;c.lineWidth=2;for(let i=0;i<n;i++){const a=i*TAU/n+.2;line(c,f.x+Math.cos(a)*r*.8,f.y+Math.sin(a)*r*.8,f.x+Math.cos(a)*r*1.1,f.y+Math.sin(a)*r*1.1);c.stroke();}if(f.final){c.globalAlpha=q*.6;for(let i=0;i<8;i++){const a=i*TAU/8;circle(c,f.x+Math.cos(a)*r*.7,f.y+Math.sin(a)*r*.7,8*q);c.stroke();}}}
  }c.restore();
 }
};
