import {Game} from './game.js?v=cat5';
import {WORLD,ENEMY_TYPES} from './data.js?v=cat5';
const TAU=Math.PI*2;
const alpha=(c,n)=>c+Math.round(Math.max(0,Math.min(1,n))*255).toString(16).padStart(2,'0');
function poly(c,r,n,offset=0,inner=1){c.beginPath();for(let i=0;i<n;i++){const a=i*TAU/n+offset,rr=i%2?r*inner:r;c.lineTo(Math.cos(a)*rr,Math.sin(a)*rr);}c.closePath();}
function glow(c,x,y,r,color){const g=c.createRadialGradient(x,y,1,x,y,r);g.addColorStop(0,alpha(color,.15));g.addColorStop(1,alpha(color,0));c.fillStyle=g;c.fillRect(x-r,y-r,r*2,r*2);}

export const signalVisuals={
  render(delta){this.hitStop=Math.max(0,(this.hitStop||0)-delta);this.glitch=Math.max(0,(this.glitch||0)-delta);Game.prototype.render.call(this,delta);
    const c=this.ctx;c.save();c.setTransform(this.dpr,0,0,this.dpr,0,0);
    // Subtle phosphor lines are static, so the treatment never masks telegraphs.
    c.globalAlpha=.055;c.fillStyle='#050708';for(let y=0;y<this.h;y+=4)c.fillRect(0,y,this.w,1);c.globalAlpha=1;
    if(this.overdrive>0&&this.state!=='menu'){c.strokeStyle='#d6ff6780';c.lineWidth=2;c.strokeRect(9,9,this.w-18,this.h-18);c.font='12px monospace';c.textAlign='center';c.fillStyle='#d9ff7f';c.fillText('우다다 타임!',this.w/2,this.h-113);}
    if(this.glitch>0&&this.settings.shake){c.globalAlpha=Math.min(.16,this.glitch*.2);c.fillStyle='#cafa80';const y=(this.visualTime*710)%this.h;c.fillRect(0,y,this.w,2);c.fillStyle='#ff537f';c.fillRect(this.w*.15,(y+200)%this.h,this.w*.6,1);c.globalAlpha=1;}
    c.restore();
  },
  drawFloor(c){
    const left=this.camera.x-this.w/(2*this.zoom),top=this.camera.y-this.h/(2*this.zoom),right=left+this.w/this.zoom,bottom=top+this.h/this.zoom;
    if(this.groundImage?.complete&&this.groundImage.naturalWidth){c.globalAlpha=this.state==='menu'?.8:.57;c.drawImage(this.groundImage,-WORLD,-WORLD,WORLD*2,WORLD*2);c.globalAlpha=1;}
    c.strokeStyle='#98bb8730';c.lineWidth=.7;for(let x=Math.floor(left/240)*240;x<right;x+=240)for(let y=Math.floor(top/240)*240;y<bottom;y+=240){c.beginPath();c.moveTo(x-4,y);c.lineTo(x+4,y);c.moveTo(x,y-4);c.lineTo(x,y+4);c.stroke();}
    c.save();c.strokeStyle='#b6ce8d28';c.lineWidth=1;for(let i=0;i<4;i++){const y=-1000+i*675;c.beginPath();for(let x=left;x<right;x+=12){const wave=Math.sin(x*.023+i*1.9)*5+Math.sin(x*.052)*2;c.lineTo(x,y+wave);}c.stroke();}c.restore();
    for(const s of this.scars||[]){if(!this.visible(s.x,s.y,s.r))continue;c.save();c.translate(s.x,s.y);c.globalAlpha=Math.min(.45,s.life*.15);c.fillStyle='#050b0d';poly(c,s.r*1.2,7,0,.65);c.fill();c.strokeStyle=s.color;c.lineWidth=.7;for(let i=0;i<4;i++){const a=i*1.7+s.x;c.beginPath();c.moveTo(Math.cos(a)*s.r*.5,Math.sin(a)*s.r*.5);c.lineTo(Math.cos(a)*s.r*1.5,Math.sin(a)*s.r*1.5);c.stroke();}c.restore();}
    c.save();c.translate(0,0);c.strokeStyle='#b6d29365';c.lineWidth=1.3;for(const r of [147,158,176]){c.beginPath();c.arc(0,0,r,0,TAU);c.stroke();}for(let i=0;i<48;i++){const a=i*TAU/48,r=181;c.beginPath();c.moveTo(Math.cos(a)*r,Math.sin(a)*r);c.lineTo(Math.cos(a)*(r+(i%4===0?12:5)),Math.sin(a)*(r+(i%4===0?12:5)));c.stroke();}c.rotate(Math.PI/4);c.strokeRect(-22,-22,44,44);c.strokeRect(-13,-13,26,26);c.rotate(-Math.PI/4);c.fillStyle='#c2d8ad';c.textAlign='center';c.font='12px monospace';c.fillText('편의점 출입구',0,222);c.restore();
    c.strokeStyle='#ff695b77';c.lineWidth=3;c.strokeRect(-WORLD,-WORLD,WORLD*2,WORLD*2);c.setLineDash([9,25]);c.lineWidth=12;c.strokeStyle='#ed6e452e';c.strokeRect(-WORLD-9,-WORLD-9,WORLD*2+18,WORLD*2+18);c.setLineDash([]);
    c.fillStyle='#060911';if(left<-WORLD)c.fillRect(left,top,-WORLD-left,bottom-top);if(right>WORLD)c.fillRect(WORLD,top,right-WORLD,bottom-top);if(top<-WORLD)c.fillRect(left,top,right-left,-WORLD-top);if(bottom>WORLD)c.fillRect(left,WORLD,right-left,bottom-WORLD);
  },
  drawDemo(c){const x=220,y=-20,t=this.visualTime;glow(c,x,y,430,'#b1d562');c.save();c.translate(x,y);c.strokeStyle='#d7f98a45';for(let i=0;i<4;i++){c.lineWidth=i===2?2:1;c.beginPath();c.arc(0,0,70+i*65,i*.31+t*.025,TAU+i*.31+t*.025-.13);c.stroke();}c.rotate(t*.08);c.beginPath();c.moveTo(90,0);c.lineTo(267,0);c.stroke();c.restore();
    for(let i=0;i<9;i++){const a=i*2.35+.9,r=245+(i%3)*78;const type=['wraith','jammer','stalker','sniper','brute'][i%5];const d=ENEMY_TYPES[type];this.drawEnemy(c,{...d,x:x+Math.cos(a)*r,y:y+Math.sin(a)*r,angle:a+Math.PI,type,id:i,hp:d.hp,maxHp:d.hp,warmup:0,flash:0,phase:0});}
    this.drawPlayer(c,x,y,-.6);for(let i=0;i<3;i++){const a=t*.4+i*TAU/3;this.drawDrone(c,x+Math.cos(a)*94,y+Math.sin(a)*94,a);}
    c.save();c.translate(x,y);c.strokeStyle='#d9ff8777';c.lineWidth=1.3;c.beginPath();for(let px=-120;px<120;px+=2){const envelope=Math.exp(-px*px/1200),h=Math.sin(px*.25+t*2.3)*envelope*20;c.lineTo(px,125+h);}c.stroke();c.restore();
  },
  drawPlayer(c,x,y,a){this.drawAim(c,x,y,a);const p=this.player,t=this.visualTime,moving=this.state==='menu'||Math.hypot(this.touch?.x||0,this.touch?.y||0)>0||this.keys.size>0;const hot=this.overdrive>0;c.save();c.translate(x,y);if(p.invuln>0&&Math.floor(t*16)%2===0&&this.state!=='menu')c.globalAlpha=.65;glow(c,0,0,70,hot?'#d3ff5b':'#91dfc9');c.rotate(a);
    // A small antenna operator with layered platework and a split signal cape.
    c.fillStyle='#070b10';c.beginPath();c.ellipse(-4,5,22,16,0,0,TAU);c.fill();const flutter=Math.sin(t*(moving?15:3))*3;
    c.fillStyle='#233b38';c.strokeStyle='#819278';c.lineWidth=1;c.beginPath();c.moveTo(-7,-12);c.lineTo(-24,-16+flutter);c.lineTo(-19,-4);c.lineTo(-27,5+flutter);c.lineTo(-22,17);c.lineTo(-8,12);c.closePath();c.fill();c.stroke();
    c.fillStyle=this.classId==='warden'?'#b8bd91':'#dee2ba';c.strokeStyle='#e9eccf';c.lineWidth=1.3;c.beginPath();c.moveTo(12,-7);c.lineTo(4,-13);c.lineTo(-10,-11);c.lineTo(-13,-6);c.lineTo(-13,8);c.lineTo(-4,12);c.lineTo(10,7);c.closePath();c.fill();c.stroke();
    c.fillStyle='#334840';c.fillRect(-9,-8,7,16);c.fillStyle=hot?'#dcff58':'#bde792';c.fillRect(-8,-5,3,10);c.fillStyle='#101c22';c.beginPath();c.ellipse(6,0,8,7,0,0,TAU);c.fill();c.strokeStyle='#d3f5cc';c.stroke();c.strokeStyle=hot?'#e6ff6b':'#96f0e1';c.lineWidth=2.5;c.beginPath();c.moveTo(7,-4);c.lineTo(10,0);c.lineTo(7,4);c.stroke();
    c.fillStyle='#d9e3c2';c.fillRect(3,8,25,5);c.fillStyle='#142422';c.fillRect(18,9,10,3);if(this.classId==='warden'){c.fillStyle='#baccb0';c.fillRect(7,14,18,3);}c.strokeStyle='#c4ce9a';c.lineWidth=1;c.beginPath();c.moveTo(-7,-10);c.lineTo(-16,-24);c.stroke();c.fillStyle='#d9ff89';c.beginPath();c.arc(-16,-24,2.5,0,TAU);c.fill();
    c.rotate(-a);c.strokeStyle=hot?'#d8ff6988':'#d5efaa55';c.lineWidth=1;c.beginPath();c.arc(0,0,30,-.3,.85);c.arc(0,0,30,2.6,3.5);c.stroke();if(this.u.rail&&this.railTimer<.5){c.strokeStyle='#e6fba8';c.beginPath();c.arc(0,0,35,-Math.PI/2,-Math.PI/2+TAU*(1-this.railTimer/.5));c.stroke();}c.restore();
  },
  drawDrone(c,x,y,a){c.save();c.translate(x,y);c.rotate(a);c.strokeStyle='#c49330';c.lineWidth=1.5;c.fillStyle='#132e2c';c.beginPath();c.moveTo(12,0);c.lineTo(0,-7);c.lineTo(-11,0);c.lineTo(0,7);c.closePath();c.fill();c.stroke();c.fillStyle='#e2ffb1';c.fillRect(-2,-2,5,4);c.strokeStyle='#95d8d4';c.lineWidth=1;c.beginPath();c.moveTo(-5,-9);c.lineTo(8,-5);c.moveTo(-5,9);c.lineTo(8,5);c.stroke();c.restore();},
  drawOrbits(c){if(!this.u.orbit)return;c.strokeStyle='#c0f49924';c.lineWidth=1;c.setLineDash([2,9]);c.beginPath();c.arc(this.player.x,this.player.y,this.evolved.nova?101:82,0,TAU);if(this.evolved.nova)c.arc(this.player.x,this.player.y,137,0,TAU);c.stroke();c.setLineDash([]);for(const o of this.orbitPoints())this.drawDrone(c,o.x,o.y,o.a);},
  drawFields(c){const p=this.player;if(this.u.field){const r=100+this.u.field*13+(this.evolved.absolute?55:0);c.save();c.translate(p.x,p.y);c.fillStyle='#72c9e00b';c.strokeStyle='#a6deeb55';c.lineWidth=1;poly(c,r,6,this.t*.04);c.fill();c.stroke();c.strokeStyle='#a6deeb22';poly(c,r*.89,6,-this.t*.04);c.stroke();for(let i=0;i<12;i++){const a=i*TAU/12+this.t*.12;c.beginPath();c.moveTo(Math.cos(a)*(r-9),Math.sin(a)*(r-9));c.lineTo(Math.cos(a)*r,Math.sin(a)*r);c.stroke();}c.restore();}
    for(const trap of this.traps){if(!this.visible(trap.x,trap.y,90))continue;c.save();c.translate(trap.x,trap.y);const armed=trap.age>trap.arm;c.strokeStyle=trap.echo?'#c8f994':armed?'#cb9dff':'#8d7998';c.lineWidth=1.6;c.rotate(this.visualTime*.4);poly(c,14,6,0,.7);c.stroke();c.fillStyle='#ccb2fc';c.fillRect(-2,-2,4,4);if(armed){c.globalAlpha=.18;c.beginPath();c.arc(0,0,48,0,TAU);c.stroke();}c.restore();}
    for(const w of this.wells){if(!this.visible(w.x,w.y,w.r))continue;glow(c,w.x,w.y,w.r,'#ab78ff');c.save();c.translate(w.x,w.y);c.strokeStyle='#b8a2ff88';c.lineWidth=1.3;for(let i=0;i<4;i++){const r=20+((this.visualTime*45+i*35)%135);c.globalAlpha=1-r/160;c.beginPath();c.ellipse(0,0,r,r*.55,this.visualTime*.8+i*.3,0,TAU);c.stroke();}c.globalAlpha=1;c.fillStyle='#050b14';c.beginPath();c.arc(0,0,15,0,TAU);c.fill();c.strokeStyle='#d4b8ff';c.stroke();c.restore();}
  },
  drawEnemy(c,e){c.save();c.translate(e.x,e.y);const r=e.r,t=this.visualTime,hot=e.flash>0;if(e.warmup>0){c.globalAlpha=.55;c.strokeStyle=e.color;c.lineWidth=1;c.setLineDash([4,5]);c.beginPath();c.arc(0,0,r+18,0,TAU);c.stroke();c.setLineDash([]);c.globalAlpha=.22;}
    if(e.type==='jammer'&&e.warmup<=0){c.fillStyle='#9a6fd80b';c.strokeStyle='#aa91dd48';c.lineWidth=1;c.beginPath();c.arc(0,0,180,0,TAU);c.fill();c.stroke();c.beginPath();c.arc(0,0,40+(t*38)%138,0,TAU);c.stroke();}
    c.rotate(e.angle);c.fillStyle='#090e15';c.strokeStyle=hot?'#ffffff':e.color;c.lineWidth=e.boss?2.6:1.7;
    if(e.boss){glow(c,0,0,r*2.5,e.exposed>0?'#d9ff71':'#fd6175');c.save();c.rotate(t*.13);poly(c,r,12,0,.78);c.fill();c.stroke();c.strokeStyle=hot?'#fff7cb':e.color+'99';for(let i=0;i<8;i++){c.save();c.rotate(i*TAU/8);c.beginPath();c.moveTo(r*.62,-7);c.lineTo(r*1.18,-5);c.lineTo(r*1.28,0);c.lineTo(r*1.18,5);c.lineTo(r*.62,7);c.stroke();c.restore();}c.restore();c.strokeStyle=e.color;c.lineWidth=1.2;c.beginPath();c.arc(0,0,r*.58,0,TAU);c.arc(0,0,r*.69,0,TAU);c.stroke();c.fillStyle=e.exposed>0?'#dbff7c':'#ffad91';c.beginPath();c.ellipse(0,0,r*.35,r*.16,Math.PI/2,0,TAU);c.fill();c.fillStyle='#0b141a';c.beginPath();c.ellipse(0,0,r*.19,r*.08,Math.PI/2,0,TAU);c.fill();}
    else if(e.type==='sniper'){c.beginPath();c.moveTo(r+9,0);c.lineTo(-r,-r*.7);c.lineTo(-r*.6,0);c.lineTo(-r,r*.7);c.closePath();c.fill();c.stroke();c.strokeStyle='#ffe5dc';c.lineWidth=1;c.beginPath();c.moveTo(-8,0);c.lineTo(18,0);c.stroke();c.strokeStyle=e.color+'70';c.beginPath();c.moveTo(-8,-15);c.lineTo(4,-8);c.moveTo(-8,15);c.lineTo(4,8);c.stroke();}
    else if(e.type==='jammer'){c.rotate(t*.2);poly(c,r,8,0,.65);c.fill();c.stroke();c.rotate(-t*.4);poly(c,r*.62,4,Math.PI/4);c.stroke();c.fillStyle='#cfb6ff';c.beginPath();c.arc(0,0,5,0,TAU);c.fill();}
    else if(e.type==='brute'||e.type==='elite'){poly(c,r,6,.5);c.fill();c.stroke();c.lineWidth=3.5;c.beginPath();c.arc(0,0,r*.76,-1.1,1.1);c.stroke();c.lineWidth=1;for(let i=-1;i<=1;i++){c.beginPath();c.moveTo(-r*.5,i*6);c.lineTo(r*.25,i*6);c.stroke();}}
    else if(e.type==='spitter'||e.type==='splitter'){c.beginPath();for(let i=0;i<=24;i++){const a=i*TAU/24,rr=r*(1+Math.sin(a*5+t*2+e.id)*.13);c.lineTo(Math.cos(a)*rr,Math.sin(a)*rr);}c.fill();c.stroke();for(let i=0;i<3;i++){const a=i*TAU/3;c.beginPath();c.arc(Math.cos(a)*r*.4,Math.sin(a)*r*.4,3.5,0,TAU);c.stroke();}}
    else{c.beginPath();c.moveTo(r+2,0);c.lineTo(-r*.3,-r*.75);c.lineTo(-r,-r*.6);c.lineTo(-r*.6,0);c.lineTo(-r,r*.6);c.lineTo(-r*.3,r*.75);c.closePath();c.fill();c.stroke();const legs=e.type==='wraith'?3:2;for(let i=0;i<legs;i++)for(const side of [-1,1]){const x=-r*.5+i*7,step=Math.sin(t*9+e.id+i)*3;c.beginPath();c.moveTo(x,side*r*.55);c.lineTo(x-5+step,side*(r+4));c.lineTo(x-10+step,side*(r+5));c.stroke();}}
    if(!e.boss){c.fillStyle=hot?'#fffce8':e.color;c.beginPath();c.arc(r*.16,0,e.type==='elite'?5:3,0,TAU);c.fill();}
    c.restore();
    if(e.shielded){c.strokeStyle='#b4a0ff99';c.lineWidth=1.4;c.beginPath();c.arc(e.x,e.y,r+7,-.8,1.9);c.arc(e.x,e.y,r+7,2.3,5.2);c.stroke();}
    if(e.chill>0){c.strokeStyle='#9ce8ff88';c.lineWidth=1;c.strokeRect(e.x-r*.6,e.y-r*.6,r*1.2,r*1.2);}
    if(e.burn>0&&this.settings.particles){c.fillStyle='#ffb47d';for(let i=0;i<3;i++){const phase=(t*3+i*.33)%1;c.globalAlpha=1-phase;c.fillRect(e.x+Math.sin(i*3+e.id)*r*.6,e.y-phase*r-r*.2,2,5);}c.globalAlpha=1;}
    if(e.type==='charger'&&e.chargeTimer>.38){c.strokeStyle='#ff978ea0';c.lineWidth=2;c.setLineDash([9,9]);c.beginPath();c.moveTo(e.x,e.y);c.lineTo(e.x+e.chargeX*230,e.y+e.chargeY*230);c.stroke();c.setLineDash([]);}
    if(!e.boss&&e.hp<e.maxHp&&e.maxHp>100){c.fillStyle='#432a34';c.fillRect(e.x-r,e.y-r-12,r*2,3);c.fillStyle=e.color;c.fillRect(e.x-r,e.y-r-12,r*2*Math.max(0,e.hp/e.maxHp),3);}
  },
  drawHazards(c){Game.prototype.drawHazards.call(this,c);
    for(const l of this.lines){const dx=l.end.x-l.x,dy=l.end.y-l.y,a=Math.atan2(dy,dx),len=Math.hypot(dx,dy);c.save();c.translate(l.x,l.y);c.rotate(a);const warning=l.delay>0;c.fillStyle=warning?'#ff527710':'#ff719666';c.fillRect(0,-l.width*.5,len,l.width);c.strokeStyle=warning?'#ff6b98b8':'#ffe5c7';c.lineWidth=warning?1.5:l.width*.55;if(warning)c.setLineDash([9,10]);c.beginPath();c.moveTo(0,0);c.lineTo(len,0);c.stroke();c.setLineDash([]);if(warning){const q=Math.max(0,1-l.delay/l.initialDelay);c.fillStyle='#ffb4c4';c.fillRect(len*q-5,-3,10,6);}c.restore();}
    for(const w of this.waves){if(!this.visible(w.x,w.y,w.r+20))continue;const start=w.gap+w.gapWidth/2,end=w.gap+TAU-w.gapWidth/2;c.save();c.translate(w.x,w.y);c.strokeStyle=w.delay>0?'#ff8aa06b':'#ff7791';c.lineWidth=w.delay>0?1.5:5;c.beginPath();c.arc(0,0,w.r,start,end);c.stroke();c.strokeStyle='#ff799126';c.lineWidth=15;c.stroke();c.strokeStyle='#d3f3a0a8';c.lineWidth=2;c.beginPath();for(const a of [start,end]){c.moveTo(Math.cos(a)*(w.r-18),Math.sin(a)*(w.r-18));c.lineTo(Math.cos(a)*(w.r+18),Math.sin(a)*(w.r+18));}c.stroke();c.fillStyle='#d6ebba';c.textAlign='center';c.font='12px sans-serif';if(w.delay>0)c.fillText('파동 수축',0,-w.r-20);c.restore();}
  },
  drawBullets(c){c.save();c.lineCap='round';for(const b of this.bullets){if(!this.visible(b.x,b.y,30))continue;const a=Math.atan2(b.vy,b.vx),length=b.type==='rocket'?22:19,col=this.overdrive>0?'#d49229':b.color;c.strokeStyle=col+'25';c.lineWidth=b.type==='rocket'?11:6;c.beginPath();c.moveTo(b.x-Math.cos(a)*length*1.5,b.y-Math.sin(a)*length*1.5);c.lineTo(b.x,b.y);c.stroke();c.strokeStyle=col;c.lineWidth=b.type==='rocket'?4:2;c.stroke();c.fillStyle='#efffdb';c.beginPath();c.arc(b.x,b.y,b.type==='rocket'?3:1.6,0,TAU);c.fill();}for(const b of this.hostile){if(!this.visible(b.x,b.y,20))continue;c.fillStyle=b.color+'20';c.beginPath();c.arc(b.x,b.y,b.r+6,0,TAU);c.fill();c.fillStyle='#11151e';c.strokeStyle=b.color;c.lineWidth=2;c.beginPath();c.arc(b.x,b.y,b.r+1,0,TAU);c.fill();c.stroke();c.fillStyle='#ffd8c2';c.beginPath();c.arc(b.x,b.y,1.5,0,TAU);c.fill();}c.restore();},
  drawEffects(c){for(const f of this.fx){const q=Math.max(0,f.life/f.max);c.save();c.globalAlpha=q;c.strokeStyle=f.color;c.fillStyle=f.color;c.lineWidth=1.5;
      if(f.kind==='rail'){c.lineWidth=22*q;c.globalAlpha=q*.14;c.beginPath();c.moveTo(f.x,f.y);c.lineTo(f.tx,f.ty);c.stroke();c.globalAlpha=q;c.lineWidth=4*q+1;c.stroke();c.strokeStyle='#fffce9';c.lineWidth=1;c.stroke();}
      else if(f.kind==='muzzle'){c.translate(f.x,f.y);c.rotate(f.a);c.beginPath();c.moveTo(24,6);c.lineTo(42,10);c.lineTo(27,15);c.lineTo(30,9);c.closePath();c.fill();}
      else if(['slash','spark','shatter','collapse','burst'].includes(f.kind)){c.translate(f.x,f.y);if(f.kind==='slash'){c.rotate(f.a);c.lineWidth=3;c.beginPath();c.moveTo(-20,-12);c.lineTo(f.r,0);c.moveTo(-20,12);c.lineTo(f.r,0);c.stroke();}
        else if(f.kind==='collapse'){for(let i=0;i<3;i++){c.rotate(.8);c.beginPath();c.ellipse(0,0,f.r*q*(1-i*.16),f.r*q*.28,0,0,TAU);c.stroke();}}
        else{const n=f.kind==='burst'?14:f.kind==='shatter'?9:5;const radius=f.r*(1-q*.65);for(let i=0;i<n;i++){const a=i*TAU/n+f.x;c.beginPath();c.moveTo(Math.cos(a)*radius*.35,Math.sin(a)*radius*.35);c.lineTo(Math.cos(a)*radius,Math.sin(a)*radius);if(f.kind==='shatter'){c.lineTo(Math.cos(a+.09)*radius*.7,Math.sin(a+.09)*radius*.7);c.closePath();c.fill();}else c.stroke();}if(f.kind==='burst'){c.globalAlpha=q*.14;c.beginPath();c.arc(0,0,radius*.8,0,TAU);c.fill();}}}
      else if(f.kind==='ring'){c.lineWidth=2;c.beginPath();c.arc(f.x,f.y,f.r*(1-q*.8),0,TAU);c.stroke();}
      else if(f.kind==='ghost'){c.translate(f.x,f.y);c.rotate(f.angle);c.globalAlpha=q*.3;c.fillRect(-17,-10,30,20);}
      else if(f.kind==='particle'){c.fillRect(f.x-f.size/2,f.y-f.size/2,f.size,f.size);}
      c.restore();}
    for(const f of this.texts){c.globalAlpha=Math.max(0,f.life/f.max);c.fillStyle=f.color;c.font='600 '+f.size+'px monospace';c.textAlign='center';c.fillText(f.text,f.x,f.y);}c.globalAlpha=1;
  }
};
