// Read-only canvas layers. Low detail retains recognizable skill silhouettes.
const TAU=Math.PI*2;
function path(c,points){c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));}
function star(c,r){path(c,Array.from({length:10},(_,i)=>{const a=i*Math.PI/5-Math.PI/2,s=i%2?r*.45:r;return [Math.cos(a)*s,Math.sin(a)*s];}));c.closePath();c.fill();c.stroke();}
function paw(c){c.beginPath();c.ellipse(0,3,5,4,0,0,TAU);c.fill();for(const [x,y] of [[-5,-3],[0,-5],[5,-3]]){c.beginPath();c.arc(x,y,2.3,0,TAU);c.fill();}}
export const skillVisuals={
 drawCatSkills(c){const t=this.visualTime,full=this.settings.particles;c.save();c.lineCap='round';for(const z of this.skillObjects||[]){if(!this.visible(z.x,z.y,(z.r||30)+40))continue;const fade=Math.min(1,z.life/.3);c.save();c.translate(z.x,z.y);c.globalAlpha=fade;c.lineWidth=1.5;
 if(z.kind==='charge'){const q=1-Math.max(0,z.life/z.max);c.translate(0,-(z.r||24)-12);c.fillStyle='#ffe879';c.strokeStyle='#fff5c5';c.globalAlpha=fade*(.65+.35*Math.sin(q*q*55)**2);path(c,[[3,-13],[-8,1],[-1,1],[-4,12],[9,-3],[2,-3]]);c.closePath();c.fill();c.stroke();c.fillStyle='#8b793f';c.fillRect(-12,16,24,3);c.fillStyle='#fff0a4';c.fillRect(-12,16,24*q,3);if(full){c.strokeStyle='#ffec98';for(const side of [-1,1]){path(c,[[side*14,-5],[side*(18+q*5),0],[side*14,6]]);c.stroke();}}}
 if(z.kind==='turret'){c.fillStyle='#385e5c';c.strokeStyle='#a0e4cf';path(c,[[-20,12],[-12,2],[12,2],[20,12],[12,18],[-12,18]]);c.closePath();c.fill();c.stroke();const n=this.enemies.find(e=>!e.dead&&Math.hypot(e.x-z.x,e.y-z.y)<460),a=n?Math.atan2(n.y-z.y,n.x-z.x):0;c.rotate(a);c.fillStyle='#d6f5c1';c.fillRect(-8,-8,18,16);c.strokeRect(-8,-8,18,16);const recoil=Math.max(0,(z.tick||0)-.3)*16;c.fillStyle='#f8d795';c.fillRect(6-recoil,-4,21,8);if(full&&recoil>0){c.fillStyle='#fff5c2';path(c,[[28,-6],[36,0],[28,6]]);c.fill();}}
 if(z.kind==='satellites'){for(let i=0;i<3;i++){const a=(z.phase||0)+i*TAU/3;c.save();c.translate(Math.cos(a)*z.r,Math.sin(a)*z.r);if(full){c.strokeStyle='#bdb0ff';c.globalAlpha=fade*.4;c.lineWidth=3;path(c,[[-Math.cos(a+Math.PI/2)*24,-Math.sin(a+Math.PI/2)*24],[0,0]]);c.stroke();}c.globalAlpha=fade;c.fillStyle='#dbc6ff';c.strokeStyle='#fff3ff';c.rotate(Math.sin(t*3+i)*.18);star(c,13);c.fillStyle='#53436e';c.fillRect(-5,-2,2,3);c.fillRect(3,-2,2,3);c.restore();}}
 c.restore();}
 if(this.skillBuff?.kind==='sprint'){const p=this.player,a=Math.atan2(p.moveY||0,p.moveX||1);c.save();c.translate(p.x,p.y);c.rotate(a);c.strokeStyle='#b8ffd9';c.lineWidth=2;for(const side of [-1,1]){path(c,[[-33,side*14],[-16,side*14],[-23,side*9]]);c.stroke();}c.restore();}c.restore();},
 drawCatTrap(c,z){if(!this.visible(z.x,z.y,z.r+10))return;const q=Math.min(1,z.age/z.arm),armed=z.age>=z.arm;c.save();c.translate(z.x,z.y);c.lineWidth=1;c.strokeStyle=z.echo?'#b1edb8':'#b2a0d3';c.globalAlpha=armed?.3:.17;c.setLineDash(armed?[5,8]:[2,10]);c.beginPath();c.arc(0,0,z.r,0,TAU);c.stroke();c.setLineDash([]);c.globalAlpha=.9;c.lineWidth=2;
 if(z.echo){c.fillStyle='#b8efb1';c.save();c.rotate(-.3);paw(c);c.translate(14,-14);paw(c);c.restore();}else{c.strokeStyle='#9ee7b2';path(c,[[0,12],[0,-14*q]]);c.stroke();c.fillStyle='#86d9a4';for(const side of [-1,1]){c.beginPath();c.ellipse(side*7,1,9,4,side*.6,0,TAU);c.fill();}if(armed){c.fillStyle=this.evolved.garden?'#f3c4ff':'#e1c9ff';c.strokeStyle='#ffe8ff';c.save();c.translate(0,-15);star(c,this.evolved.garden?12:8);c.restore();}}c.restore();},
 drawCatWell(c,w){if(!this.visible(w.x,w.y,w.r))return;const full=this.settings.particles,t=this.visualTime,fade=Math.min(1,w.life/.4);c.save();c.translate(w.x,w.y);c.strokeStyle='#c5a3ef';c.lineWidth=1;c.globalAlpha=.22*fade;c.setLineDash([3,12]);c.beginPath();c.arc(0,0,w.r,0,TAU);c.stroke();c.setLineDash([]);for(let j=0;j<(full?3:2);j++){c.globalAlpha=.55*fade;c.lineWidth=full?2.5:1.5;c.beginPath();for(let i=0;i<=32;i++){const q=i/32,r=22+q*(w.r-22),a=q*TAU*1.1-t*2+j*TAU/(full?3:2);const x=Math.cos(a)*r,y=Math.sin(a)*r*.65;i?c.lineTo(x,y):c.moveTo(x,y);}c.stroke();}if(full){c.fillStyle='#efd3a3';for(let i=0;i<9;i++){const q=1-((t*.6+i/9)%1),a=i*2.4+t*1.3,r=24+q*(w.r-24);c.globalAlpha=q*fade;c.save();c.translate(Math.cos(a)*r,Math.sin(a)*r*.65);c.rotate(a);c.fillRect(-3,-2,6,4);c.restore();}}c.globalAlpha=fade;c.fillStyle='#100e24';c.strokeStyle='#eed7ff';c.lineWidth=3;c.beginPath();c.ellipse(0,0,25,17,-.3,0,TAU);c.fill();c.stroke();c.restore();},
 drawSkillBursts(c){for(const f of this.fx){if(!f.skillBurst||!this.visible(f.x,f.y,f.r))continue;const q=Math.max(0,f.life/f.max);c.save();c.translate(f.x,f.y);c.globalAlpha=q;c.strokeStyle=f.skillBurst==='ice'?'#d2f6ff':'#fff0a0';c.fillStyle=c.strokeStyle;c.lineWidth=2;for(let i=0;i<(this.settings.particles?8:4);i++){const a=i*TAU/(this.settings.particles?8:4),r=(1-q)*f.r;c.save();c.rotate(a);if(f.skillBurst==='ice'){path(c,[[r,0],[r-11,-3],[r-6,4]]);c.closePath();c.fill();}else{path(c,[[8,0],[r*.45,-5],[r*.65,5],[r,0]]);c.stroke();}c.restore();}c.restore();}}
};
