// Cosmetic-only themes. No combat state, hitboxes, timers or RNG are changed.
const TAU=Math.PI*2;
export const THEMES={bakery:{cat:'warden',name:'베이커리 후추',color:'#ffd58a',desc:'제빵사 모자·앞치마 + 버터 토스트 방어 + 빵가루 반격'},neon:{cat:'spider',name:'네온 스파이더냥',color:'#77ffe1',desc:'네온 거미 문양 + 전류가 흐르는 거미줄 + 빛나는 매듭'},moonlight:{cat:'ninja',name:'달빛 닌자냥',color:'#b9ceff',desc:'은빛 초승달 두건 + 달빛 참격 + 먹빛 잔상'}};
export function toastShape(c,x,y,r=24){c.save();c.translate(x,y);c.beginPath();c.moveTo(-r*.75,r);c.lineTo(-r*.75,-r*.2);c.bezierCurveTo(-r*1.3,-r*.9,-r*.2,-r*1.3,0,-r*.85);c.bezierCurveTo(r*.5,-r*1.4,r*1.3,-r*.7,r*.75,-r*.2);c.lineTo(r*.75,r);c.closePath();c.fillStyle='#d79040';c.fill();c.strokeStyle='#ffe3a0';c.lineWidth=3;c.stroke();c.fillStyle='#fff0bb';c.fillRect(-r*.5,-r*.25,r,r);c.fillStyle='#ffcf4f';c.save();c.rotate(-.2);c.fillRect(-r*.23,-r*.1,r*.46,r*.3);c.restore();c.restore();}
export function drawThemeScene(g,c){const id=g.cosmetics?.outfit,theme=THEMES[id];if(!theme||g.classId!==theme.cat)return;const t=g.visualTime||0,p=g.player,full=g.settings?.particles!==false;c.save();c.lineCap='round';
 if(id==='bakery'&&g.skillBuff?.kind==='guard'&&g.skillBuff.shield>0){for(let i=0;i<3;i++){const a=t*.7+i*TAU/3;c.globalAlpha=.9;toastShape(c,p.x+Math.cos(a)*40,p.y+Math.sin(a)*30,15);}c.globalAlpha=.5;c.strokeStyle='#ffdf83';c.lineWidth=2;for(let i=0;i<3;i++){const x=p.x-18+i*18;c.beginPath();c.moveTo(x,p.y-43);c.quadraticCurveTo(x+8,p.y-49,x,p.y-56);c.stroke();}}
 if(id==='bakery')for(const b of (g.beams||[]).filter(b=>b.bread).slice(-12)){const q=1-b.life/.2;toastShape(c,b.x+(b.tx-b.x)*q,b.y+(b.ty-b.y)*q,11);if(full)for(let i=0;i<4;i++){c.fillStyle=i%2?'#ffe17d':'#c88d4c';c.fillRect(b.tx+Math.cos(i*2)*q*22,b.ty+Math.sin(i*2)*q*22,3,3);}}
 if(id==='neon')for(const z of (g.skillObjects||[]).filter(z=>z.kind==='web').slice(-6)){if(g.visible&&!g.visible(z.x,z.y,z.r))continue;c.strokeStyle='#69ffdc';c.globalAlpha=.65*Math.min(1,z.life);c.lineWidth=2;const n=full?8:4;for(let i=0;i<n;i++){const a=i*TAU/n,r=z.r*((t*.5+i/n)%1);c.beginPath();c.moveTo(z.x+Math.cos(a)*r,z.y+Math.sin(a)*r);c.lineTo(z.x+Math.cos(a)*(r+12),z.y+Math.sin(a)*(r+12));c.stroke();c.save();c.translate(z.x+Math.cos(a)*z.r*.7,z.y+Math.sin(a)*z.r*.7);c.rotate(Math.PI/4);c.strokeRect(-3,-3,6,6);c.restore();}}
 if(id==='moonlight')for(const f of (g.fx||[]).filter(f=>f.kind==='slash').slice(-8)){const q=f.life/f.max;c.save();c.translate(f.x,f.y);c.rotate(f.a||0);c.globalAlpha=q*.85;c.strokeStyle='#d9e6ff';c.lineWidth=5;c.beginPath();c.arc(0,0,Math.min(80,f.r+25),-.95,.95);c.stroke();if(full){c.strokeStyle='#718bb7';c.lineWidth=2;for(let i=1;i<=3;i++){c.globalAlpha=q*(.5-i*.1);c.beginPath();c.arc(-i*12,0,Math.min(80,f.r+25),-.9,.9);c.stroke();}}c.restore();}
 c.restore();}
export function drawThemeKill(g,c,f){const id=g.cosmetics?.outfit;if(!THEMES[id]||THEMES[id].cat!==g.classId)return false;const q=f.life/.45,n=g.settings?.particles===false?3:6;c.save();c.globalAlpha=q*.8;c.strokeStyle=THEMES[id].color;c.lineWidth=2;for(let i=0;i<n;i++){const a=i*TAU/n,r=12+(1-q)*30;c.save();c.translate(f.x+Math.cos(a)*r,f.y+Math.sin(a)*r);c.rotate(a);if(id==='bakery')toastShape(c,0,0,4);else if(id==='neon'){c.rotate(Math.PI/4);c.strokeRect(-3,-3,6,6);}else{c.beginPath();c.arc(0,0,5,.5,5.2);c.stroke();}c.restore();}c.restore();return true;}
