const TAU=Math.PI*2;
function ring(c,x,y,r){c.beginPath();c.arc(x,y,Math.max(0,r),0,TAU);}
function crystal(c,x,y,r,a){c.save();c.translate(x,y);c.rotate(a);c.beginPath();c.moveTo(0,-r);c.lineTo(r*.38,0);c.lineTo(0,r);c.lineTo(-r*.38,0);c.closePath();c.stroke();c.restore();}
export const zoneFX={
 drawWebZones(c){for(const z of this.skillObjects||[]){if(z.kind!=='web'||!this.visible(z.x,z.y,z.r))continue;const full=this.settings.particles,age=Math.max(0,z.max-z.life),spread=full?Math.min(1,age/.32):1,r=z.r*spread,fade=Math.min(1,z.life/.7);c.save();c.translate(z.x,z.y);c.globalAlpha=fade;c.lineWidth=1.3;c.strokeStyle='#e4d1ff';c.fillStyle='#9875d912';ring(c,0,0,z.r);c.fill();c.globalAlpha=fade*.65;
 for(let i=0;i<12;i++){const a=i*TAU/12;c.beginPath();c.moveTo(0,0);c.lineTo(Math.cos(a)*r,Math.sin(a)*r);c.stroke();}
 for(let j=1;j<=(full?5:3);j++){const rr=r*j/(full?5:3);c.beginPath();for(let i=0;i<12;i++){const a=i*TAU/12,b=(i+1)*TAU/12,mid=(a+b)/2;if(!i)c.moveTo(Math.cos(a)*rr,Math.sin(a)*rr);c.quadraticCurveTo(Math.cos(mid)*rr*.82,Math.sin(mid)*rr*.82,Math.cos(b)*rr,Math.sin(b)*rr);}c.closePath();c.stroke();}
 if(full){c.globalAlpha=fade*.9;c.fillStyle='#f4e9ff';for(let i=0;i<12;i++){const a=i*TAU/12;ring(c,Math.cos(a)*r,Math.sin(a)*r,2.2);c.fill();}if(age<.65){c.globalAlpha=(1-age/.65)*.7;c.lineWidth=3;ring(c,0,0,z.r*Math.min(1,age/.32));c.stroke();}}
 c.restore();}}
 ,drawIceZone(c){if(!this.u.field)return;const p=this.player,r=100+this.u.field*13+(this.evolved.absolute?55:0),t=this.visualTime,full=this.settings.particles;c.save();c.strokeStyle='#b1eeff';c.lineWidth=1.5;c.globalAlpha=.3;ring(c,p.x,p.y,r);c.stroke();if(full){const grad=c.createRadialGradient(p.x,p.y,r*.5,p.x,p.y,r);grad.addColorStop(0,'#84dfff00');grad.addColorStop(.8,'#86ddff08');grad.addColorStop(1,'#b7f5ff20');c.globalAlpha=1;c.fillStyle=grad;ring(c,p.x,p.y,r);c.fill();for(let j=0;j<2;j++){const q=(t*.65+j*.5)%1;c.globalAlpha=(1-q)*.32;c.lineWidth=2;ring(c,p.x,p.y,r*(.2+.8*q));c.stroke();}c.globalAlpha=.7;const n=this.evolved.absolute?16:10;for(let i=0;i<n;i++){const a=i*TAU/n,rr=r-8+Math.sin(t*1.5+i)*3;crystal(c,p.x+Math.cos(a)*rr,p.y+Math.sin(a)*rr,this.evolved.absolute?10:6,a+t*.08);}}c.restore();}
 ,drawEnemyStatus(c,e){if(e.dead)return;const zones=(this.skillObjects||[]).filter(z=>z.kind==='web'&&z.life>0&&Math.hypot(e.x-z.x,e.y-z.y)<z.r+e.r),web=e.root>0&&zones.length>0;c.save();if(web){c.strokeStyle='#eedcff';c.globalAlpha=.7;c.lineWidth=1.3;for(let i=0;i<3;i++){c.beginPath();c.ellipse(e.x,e.y,e.r+5,e.r*.42,i*Math.PI/3,0,TAU);c.stroke();}if(this.settings.particles){const z=zones[0],a=Math.atan2(e.y-z.y,e.x-z.x);c.globalAlpha=.4;c.beginPath();c.moveTo(e.x,e.y);c.lineTo(z.x+Math.cos(a)*z.r,z.y+Math.sin(a)*z.r);c.stroke();}}
 if(e.chill>0){c.strokeStyle='#caf8ff';c.lineWidth=1.4;c.globalAlpha=Math.min(.8,e.chill*.5);const r=e.r+7;for(let i=0;i<(this.settings.particles?6:3);i++){const a=i*TAU/(this.settings.particles?6:3);crystal(c,e.x+Math.cos(a)*r,e.y+Math.sin(a)*r,5,a);}if(e.root>0&&!web){c.globalAlpha=.14;c.fillStyle='#a8ecff';ring(c,e.x,e.y,r);c.fill();}}c.restore();}
};
