const TAU=Math.PI*2;
function ring(c,x,y,r){c.beginPath();c.arc(x,y,Math.max(0,r),0,TAU);}
function crystal(c,x,y,r,a){c.save();c.translate(x,y);c.rotate(a);c.beginPath();c.moveTo(0,-r);c.lineTo(r*.38,0);c.lineTo(0,r);c.lineTo(-r*.38,0);c.closePath();c.stroke();c.restore();}
export const zoneFX={
 drawWebZones(c){for(const z of this.skillObjects||[]){if(z.kind!=='web'||!this.visible(z.x,z.y,z.r))continue;const full=this.settings.particles,age=Math.max(0,z.max-z.life),spread=full?Math.min(1,age/.32):1,r=z.r*spread,fade=Math.min(1,z.life/.7);c.save();c.translate(z.x,z.y);c.globalAlpha=fade;c.lineWidth=1.3;c.strokeStyle=this.cosmetics?.outfit==='neon'?'#79ffe1':'#e4d1ff';c.fillStyle='#9875d912';ring(c,0,0,z.r);c.fill();c.globalAlpha=fade*.65;
 for(let i=0;i<12;i++){const a=i*TAU/12;c.beginPath();c.moveTo(0,0);c.lineTo(Math.cos(a)*r,Math.sin(a)*r);c.stroke();}
 for(let j=1;j<=(full?5:3);j++){const rr=r*j/(full?5:3);c.beginPath();for(let i=0;i<12;i++){const a=i*TAU/12,b=(i+1)*TAU/12,mid=(a+b)/2;if(!i)c.moveTo(Math.cos(a)*rr,Math.sin(a)*rr);c.quadraticCurveTo(Math.cos(mid)*rr*.82,Math.sin(mid)*rr*.82,Math.cos(b)*rr,Math.sin(b)*rr);}c.closePath();c.stroke();}
 if(full){c.globalAlpha=fade*.9;c.fillStyle='#f4e9ff';for(let i=0;i<12;i++){const a=i*TAU/12;ring(c,Math.cos(a)*r,Math.sin(a)*r,2.2);c.fill();}if(age<.65){c.globalAlpha=(1-age/.65)*.7;c.lineWidth=3;ring(c,0,0,z.r*Math.min(1,age/.32));c.stroke();}}
 c.restore();}}
 ,drawIceZone(c){if(!this.u.field)return;const p=this.player,r=100+this.u.field*13+(this.evolved.absolute?55:0),t=this.visualTime,full=this.settings.particles;c.save();c.strokeStyle='#b1eeff';c.lineWidth=1.5;c.globalAlpha=.3;ring(c,p.x,p.y,r);c.stroke();if(full){const grad=c.createRadialGradient(p.x,p.y,r*.5,p.x,p.y,r);grad.addColorStop(0,'#84dfff00');grad.addColorStop(.8,'#86ddff08');grad.addColorStop(1,'#b7f5ff20');c.globalAlpha=1;c.fillStyle=grad;ring(c,p.x,p.y,r);c.fill();for(let j=0;j<2;j++){const q=(t*.65+j*.5)%1;c.globalAlpha=(1-q)*.32;c.lineWidth=2;ring(c,p.x,p.y,r*(.2+.8*q));c.stroke();}c.globalAlpha=.7;const n=this.evolved.absolute?16:10;for(let i=0;i<n;i++){const a=i*TAU/n,rr=r-8+Math.sin(t*1.5+i)*3;crystal(c,p.x+Math.cos(a)*rr,p.y+Math.sin(a)*rr,this.evolved.absolute?10:6,a+t*.08);}}c.restore();}
 ,drawEnemyStatus(c,e){if(e.dead)return;const zones=(this.skillObjects||[]).filter(z=>z.kind==='web'&&z.life>0&&Math.hypot(e.x-z.x,e.y-z.y)<z.r+e.r),web=e.root>0&&zones.length>0;c.save();if(web){c.strokeStyle='#eedcff';c.globalAlpha=.7;c.lineWidth=1.3;for(let i=0;i<3;i++){c.beginPath();c.ellipse(e.x,e.y,e.r+5,e.r*.42,i*Math.PI/3,0,TAU);c.stroke();}if(this.settings.particles){const z=zones[0],a=Math.atan2(e.y-z.y,e.x-z.x);c.globalAlpha=.4;c.beginPath();c.moveTo(e.x,e.y);c.lineTo(z.x+Math.cos(a)*z.r,z.y+Math.sin(a)*z.r);c.stroke();}}
 if(e.chill>0){c.strokeStyle='#caf8ff';c.lineWidth=1.4;c.globalAlpha=Math.min(.8,e.chill*.5);const r=e.r+7;for(let i=0;i<(this.settings.particles?6:3);i++){const a=i*TAU/(this.settings.particles?6:3);crystal(c,e.x+Math.cos(a)*r,e.y+Math.sin(a)*r,5,a);}if(e.root>0&&!web){c.globalAlpha=.14;c.fillStyle='#a8ecff';ring(c,e.x,e.y,r);c.fill();}}c.restore();}
 ,drawSupportZones(c){const t=this.visualTime,full=this.settings.particles;for(const z of this.skillObjects||[]){if(!['flame','clinic'].includes(z.kind)||!this.visible(z.x,z.y,z.r))continue;c.save();c.translate(z.x,z.y);c.lineCap='round';const fade=Math.min(1,z.life/.4);if(z.kind==='flame'){const a=z.angle??this.player.angle;c.rotate(a);c.strokeStyle='#ffb065';c.globalAlpha=.3*fade;c.lineWidth=1.3;c.beginPath();c.arc(0,0,z.r,-.72,.72);c.stroke();const count=full?9:3;for(let i=0;i<count;i++){const angle=(i/(count-1)-.5)*1.25,wave=Math.sin(t*19+i*2)*.045,len=z.r*(.75+.22*Math.sin(t*10+i)**2);c.save();c.rotate(angle+wave);for(const [width,color,alpha] of [[full?17:8,'#ff652e',.28],[7,'#ffba55',.65],[2,'#fff0ab',.85]]){c.strokeStyle=color;c.lineWidth=width;c.globalAlpha=alpha*fade;c.beginPath();c.moveTo(25,0);c.quadraticCurveTo(len*.55,Math.sin(t*12+i)*14,len,0);c.stroke();}if(full){const q=(t*1.8+i*.13)%1;c.fillStyle='#ffdf87';c.globalAlpha=(1-q)*fade;ring(c,len*q,Math.sin(t*7+i)*9,2.8*(1-q));c.fill();}c.restore();}}
 else{c.strokeStyle='#9cffe0';c.fillStyle='#91ffd411';c.globalAlpha=fade;ring(c,0,0,z.r);c.fill();c.lineWidth=2;c.globalAlpha=.65*fade;c.stroke();if(full)for(let j=0;j<3;j++){const q=(t*.65+j/3)%1;c.globalAlpha=(1-q)*.5*fade;ring(c,0,0,z.r*q);c.stroke();}c.globalAlpha=.85*fade;c.lineWidth=5;c.beginPath();c.moveTo(-13,0);c.lineTo(13,0);c.moveTo(0,-13);c.lineTo(0,13);c.stroke();if(full)for(let i=0;i<6;i++){const a=i*Math.PI/3,q=(t*.6+i*.2)%1,x=Math.cos(a)*z.r*.65,y=Math.sin(a)*z.r*.65-q*18;c.globalAlpha=(1-q)*fade;c.lineWidth=2;c.beginPath();c.moveTo(x-4,y);c.lineTo(x+4,y);c.moveTo(x,y-4);c.lineTo(x,y+4);c.stroke();}}
 c.restore();}}
 ,drawGuardShield(c){const b=this.skillBuff;if(b?.kind!=='guard'||b.shield<=0)return;const p=this.player,q=Math.max(0,Math.min(1,b.shield/(p.maxHp*.45))),flash=(b.flash||0)/.25,r=40+flash*5;c.save();c.translate(p.x,p.y);c.strokeStyle=flash>0?'#fff8d7':'#ffd792';c.fillStyle='#ffd79212';c.lineWidth=2.5;c.globalAlpha=.6+flash*.35;c.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3-Math.PI/6;if(i)c.lineTo(Math.cos(a)*r,Math.sin(a)*r);else c.moveTo(Math.cos(a)*r,Math.sin(a)*r);}c.closePath();c.fill();c.stroke();c.globalAlpha=.9;c.lineWidth=4;c.beginPath();c.arc(0,0,r+6,-Math.PI/2,-Math.PI/2+TAU*q);c.stroke();if(this.settings.particles&&flash>0){c.globalAlpha=flash*.7;c.lineWidth=1.5;ring(c,0,0,r+18*(1-flash));c.stroke();}c.restore();}

};
