import {test} from 'node:test';
import assert from 'node:assert/strict';
import {CatGame} from '../cat-game.js?v=cat9';
import {createMeta} from '../data.js?v=cat9';
import {ACTIVE_SKILLS} from '../roster.js?v=cat9';
function make(id){const g=new CatGame({getContext:()=>null},{},{play(){},ambient(){}},{particles:true,shake:false});g.start(id,createMeta());g.enemies=[];g.player.angle=0;g.player.hp=30;for(const x of [90,-90]){const e=g.spawnEnemy('brute',x,0);e.warmup=0;e.hp=e.maxHp=10000;}return g;}
test('12 active skills enforce cooldown, pause gate and retain cooldown on restore',()=>{for(const id of Object.keys(ACTIVE_SKILLS)){const g=make(id);g.state='paused';assert.equal(g.pulse(),false);g.state='playing';assert(g.pulse());assert.equal(g.pulse(),false);assert.equal(g.player.pulseCd,ACTIVE_SKILLS[id].cd);const h=make('runner');assert(h.restore(JSON.parse(JSON.stringify(g.serialize()))));assert.equal(h.player.pulseCd,g.player.pulseCd);}});
test('active skills deliver distinct combat roles',()=>{for(const id of Object.keys(ACTIVE_SKILLS)){const g=make(id),[front,back]=g.enemies;g.pulse();if(id==='engineer')assert.equal(g.traps.length,6);if(id==='warden')assert.equal(g.player.invuln,2);if(id==='spider')assert.equal(front.slow,5);if(id==='frost')assert.equal(front.chill,5);if(id==='chef')assert.equal(front.burn,5);if(id==='ninja'){assert(front.hp<10000);assert.equal(back.hp,10000);}if(id==='nurse')assert.equal(g.player.hp,30+g.player.maxHp*.25);if(id==='spark')assert.equal(g.beams.length,2);if(id==='wizard')assert.equal(g.bullets.length,16);if(id==='moon')assert.equal(g.bullets.length,5);if(id==='astro'){assert.equal(g.wells[0].life,4);g.updateTraps(.1);assert(front.x>90);}if(id==='runner')assert(front.x>90);}});
test('death feedback occurs once and respects particle setting',()=>{const g=make('runner'),e=g.enemies[0];g.kill(e);const n=g.fx.length;assert(g.fx.some(f=>f.kind==='shatter'));g.kill(e);assert.equal(g.fx.length,n);const h=make('runner');h.settings.particles=false;h.kill(h.enemies[0]);assert(!h.fx.some(f=>f.kind==='shatter'));});
