import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Sound} from '../audio.js';
import {normalizeMeta,createMeta} from '../data.js?v=cat21';
test('score schedules musical layers and does not catch up a backgrounded clock',()=>{const s=new Sound({sound:true});s.ctx={state:'running',currentTime:1};s.mode='playing';const notes=[];s.tone=(...a)=>notes.push(a);s.noise=()=>{};s.ambient(1/60,0);assert(notes.length>0);assert(notes.every(n=>n[6]==='music'));assert(s.step<=3);s.ctx.currentTime=1000;s.ambient(1/60,0);assert(s.step<=6);const before=s.step;s.mode='paused';s.ambient(1/60,0);assert.equal(s.step,before);s.mode='playing';s.settings.sound=false;s.ambient(1/60,0);assert.equal(s.step,before);});
test('all cat shots have effects and impact bursts are rate limited',()=>{const s=new Sound({sound:true});s.ctx={state:'running',currentTime:1};const notes=[];s.tone=(...a)=>notes.push(a);s.noise=()=>notes.push('noise');for(const id of ['web','ice','pierce','flame','heal','chain','stars','gravity','return']){s.ctx.currentTime++;const before=notes.length;s.play('weapon-'+id);assert(notes.length>before,id);}s.play('impact');const n=notes.length;for(let i=0;i<50;i++)s.play('impact');assert.equal(notes.length,n);});
test('independent music/effect levels preserve zero and migrate old settings',()=>{const old=normalizeMeta({...createMeta(),settings:{sound:false,volume:.2}});assert.equal(old.settings.sound,false);assert.equal(old.settings.musicVolume,.55);const zero=normalizeMeta({...createMeta(),settings:{sound:true,volume:.2,musicVolume:0,effectsVolume:0}});assert.equal(zero.settings.musicVolume,0);assert.equal(zero.settings.effectsVolume,0);});
test('noise has a soft attack and filtered spectrum; effects boost preserves explicit mute',()=>{const events=[],param=()=>({value:0,setValueAtTime:(...a)=>events.push(['set',...a]),linearRampToValueAtTime:(...a)=>events.push(['ramp',...a]),exponentialRampToValueAtTime(){},setTargetAtTime:(...a)=>events.push(['target',...a])});const s=new Sound({sound:true,volume:.3,effectsVolume:0,musicVolume:0});const filter={frequency:param(),Q:param(),connect(){},disconnect(){}};s.ctx={state:'running',currentTime:1,createBufferSource:()=>({connect(){},start(){},stop(){}}),createGain:()=>({gain:param(),connect(){}}),createBiquadFilter:()=>filter};s.effects={gain:param()};s.master={gain:param()};s.music={gain:param()};s.noise(.04,.1,6500);assert.equal(filter.type,'bandpass');assert.equal(filter.frequency.value,2600);assert(events.some(e=>e[0]==='ramp'&&e[1]===.1*.45));s.sync();assert.equal(events.at(-1)[1],0);s.settings.effectsVolume=.8;s.sync();assert.equal(events.at(-1)[1],.8*1.65);});
test('electrical sounds avoid harsh square and saw waves and explosions throttle overlap',()=>{const s=new Sound({sound:true});s.ctx={state:'running',currentTime:1};const tones=[];s.tone=(...a)=>tones.push(a);s.noise=()=>{};s.play('arc');s.play('weapon-chain');assert(tones.every(t=>!['square','sawtooth'].includes(t[2])));s.play('explode');const count=tones.length;for(let i=0;i<30;i++)s.play('explode');assert.equal(tones.length,count);});
