import {test} from 'node:test';import assert from 'node:assert/strict';
import {specialState,refill,reserve,refund,settle,configureSpecial,REFILL_MS} from '../special-shift.js';
import {CatGame} from '../cat-game.js';import {createMeta} from '../data.js';
test('ticket cap, fractional recovery, rollback and reload',()=>{const s=specialState(null,1000);assert.equal(s.tickets,3);reserve(s,'a',1000);assert.equal(s.tickets,2);assert(!reserve(s,'b',1000));settle(s,'a',{won:true,time:240});refill(s,1000+REFILL_MS-1);assert.equal(s.tickets,2);refill(s,1000+REFILL_MS);assert.equal(s.tickets,3);reserve(s,'b',1000+REFILL_MS);refill(s,0);assert.equal(s.tickets,2);const restored=specialState(JSON.parse(JSON.stringify(s)),1000+2*REFILL_MS);assert.equal(restored.tickets,3);});
test('settlement is once only; first failure refund and abandonment',()=>{const s=specialState(null,0);reserve(s,'a',0);assert.deepEqual(settle(s,'a',{time:85}),{shards:1,retry:true});assert.equal(s.tickets,3);assert.equal(settle(s,'a',{won:true,time:240}),null);reserve(s,'b',0);assert.deepEqual(settle(s,'b',{time:1}),{shards:0,retry:false});reserve(s,'c',0);assert.deepEqual(settle(s,'c',{abandoned:true,time:240}),{shards:0,retry:false});assert.equal(s.shards,1);assert.equal(s.wins,0);});
test('missing run refunds once and full-clear gives four stamps',()=>{const s=specialState(null,0);reserve(s,'broken',0);assert(refund(s));assert(!refund(s));assert.equal(s.tickets,3);reserve(s,'clear',0);settle(s,'clear',{won:true,time:240});assert.equal(s.shards,4);assert.equal(s.wins,1);});
const make=(cb={})=>new CatGame({getContext:()=>null},cb,{play(){},ambient(){}},{particles:false});
test('special mode has short events, survives restore and ends at four minutes',()=>{let result=null;const g=make({finish:d=>result=d});g.start('runner',createMeta());configureSpecial(g);assert.equal(g.events.at(-1).t,180);assert(g.relays.every(r=>r.unlock>240));g.t=239.99;g.pendingLevels=0;g.enemies=[];g.spawnTimer=999;g.nextInterference=999;const saved=JSON.parse(JSON.stringify(g.serialize()));const restored=make({finish:d=>result=d});assert(restored.restore(saved));assert.equal(restored.mode,'special');restored.update(.03);assert.equal(result.won,true);assert.equal(result.time,240);assert.equal(restored.state,'ended');restored.start('runner',createMeta());assert.equal(restored.mode,'normal');assert.equal(restored.events.at(-1).t,900);});
test('special death finishes without consuming revival tickets',()=>{let ended=0,downed=0;const g=make({finish:()=>ended++,downed:()=>downed++});g.start('runner',createMeta());configureSpecial(g);g.finish(false);assert.equal(ended,1);assert.equal(downed,0);g.finish(false);assert.equal(ended,1);});
